DROP TABLE IF EXISTS excelshortcuts;

CREATE TABLE excelshortcuts(
    int INTEGER PRIMARY KEY AUTOINCREMENT,
	shortcut VARCHAR(90),
	category VARCHAR(30),
	extension VARCHAR(0)
);

INSERT INTO excelshortcuts(shortcut,category,extension)
VALUES
('shortcut','category','extension'),
('ctrl＋w','frequently used','close a workbook。'),
('ctrl＋o','frequently used','open a workbook。'),
('alt＋h','frequently used','go to the home tab。'),
('ctrl＋s','frequently used','save a workbook。'),
('ctrl＋c','frequently used','copy selection。'),
('ctrl＋v','frequently used','paste selection。'),
('ctrl＋z','frequently used','undo recent action。'),
('delete','frequently used','remove cell contents。'),
('alt＋h、 h','frequently used','choose a fill color。'),
('ctrl＋x','frequently used','cut selection。'),
('alt＋n','frequently used','go to the insert tab。'),
('ctrl＋b','frequently used','apply bold formatting。'),
('alt＋h、 a、 c','frequently used','center align cell contents。'),
('alt＋p','frequently used','go to the page layout tab。'),
('alt＋a','frequently used','go to the data tab。'),
('alt＋w','frequently used','go to the view tab。'),
('shift＋f10 or windows menu key','frequently used','open the context menu。'),
('alt＋h、 b','frequently used','add borders。'),
('alt＋h、 d、 c','frequently used','delete column。'),
('alt＋m','frequently used','go to the formula tab。'),
('ctrl＋9','frequently used','hide the selected rows。'),
('ctrl＋0','frequently used','hide the selected columns。'),
('alt＋q、 then enter the search term。','ribbon keys','move to the tell me or search field on the ribbon and type a search term for assistance or help content。'),
('alt＋f','ribbon keys','open the file menu。'),
('alt＋h','ribbon keys','open the home tab and format text and numbers and use the find tool。'),
('alt＋n','ribbon keys','open the insert tab and insert pivottables、 charts、 addーins、 sparklines、 pictures、 shapes、 headers、 or text boxes。'),
('alt＋p','ribbon keys','open the page layout tab and work with themes、 page setup、 scale、 and alignment。'),
('alt＋m','ribbon keys','open the formulas tab and insert、 trace、 and customize functions and calculations。'),
('alt＋a','ribbon keys','open the data tab and connect to、 sort、 filter、 analyze、 and work with data。'),
('alt＋r','ribbon keys','open the review tab and check spelling、 add notes and threaded comments、 and protect sheets and workbooks。'),
('alt＋w','ribbon keys','open the view tab and preview page breaks and layouts、 show and hide gridlines and headings、 set zoom magnification、 manage windows and panes、 and view macros。'),
('alt or f10。 to move to a different tab、 use access keys or the arrow keys。','keyboard ribbon','select the active tab on the ribbon and activate the access keys。'),
('tab key or shift＋tab','keyboard ribbon','move the focus to commands on the ribbon or addーin pane。'),
('arrow keys','keyboard ribbon','move down、 up、 left、 or right、 respectively、 among the items on the ribbon。'),
('ctrl＋shift＋f10','keyboard ribbon','show the tooltip for the ribbon element currently in focus。'),
('spacebar or enter','keyboard ribbon','activate a selected button。'),
('down arrow key','keyboard ribbon','open the list for a selected command。'),
('alt＋down arrow key','keyboard ribbon','open the menu for a selected button。'),
('down arrow key','keyboard ribbon','when a menu or submenu is open、 move to the next command。'),
('ctrl＋f1','keyboard ribbon','expand or collapse the ribbon。'),
('shift＋f10','keyboard ribbon','open a context menu。'),
('windows key','keyboard ribbon','or、 on a windows keyboard、 the windows menu key （usually between the alt gr and right ctrl keys）'),
('left arrow key','keyboard ribbon','move to the submenu when a main menu is open or selected。'),
('ctrl＋left or right arrow key','keyboard ribbon','move from one group of controls to another。'),
('shift＋tab','cell navigation','move to the previous cell in a worksheet or the previous option in a dialog box。'),
('up arrow key','cell navigation','move one cell up in a worksheet。'),
('down arrow key','cell navigation','move one cell down in a worksheet。'),
('left arrow key','cell navigation','move one cell left in a worksheet。'),
('right arrow key','cell navigation','move one cell right in a worksheet。'),
('ctrl＋arrow key','cell navigation','move to the edge of the current data region in a worksheet。'),
('end、 arrow key','cell navigation','enter the end mode、 move to the next nonblank cell in the same column or row as the active cell、 and turn off end mode。 if the cells are blank、 move to the last cell in the row or column。'),
('ctrl＋end','cell navigation','move to the last cell on a worksheet、 to the lowest used row of the rightmost used column。'),
('ctrl＋shift＋end','cell navigation','extend the selection of cells to the last used cell on the worksheet （lower ーright corner）。'),
('home＋scroll lock','cell navigation','move to the cell in the upperーleft corner of the window when scroll lock is turned on。'),
('ctrl＋home','cell navigation','move to the beginning of a worksheet。'),
('page down','cell navigation','move one screen down in a worksheet。'),
('ctrl＋page down','cell navigation','move to the next sheet in a workbook。'),
('alt＋page down','cell navigation','move one screen to the right in a worksheet。'),
('page up','cell navigation','move one screen up in a worksheet。'),
('alt＋page up','cell navigation','move one screen to the left in a worksheet。'),
('ctrl＋page up','cell navigation','move to the previous sheet in a workbook。'),
('tab key','cell navigation','move one cell to the right in a worksheet。 or、 in a protected worksheet、 move between unlocked cells。'),
('alt＋down arrow key','cell navigation','open the list of validation choices on a cell that has data validation option applied to it。'),
('ctrl＋alt＋5、 then the tab key repeatedly','cell navigation','cycle through floating shapes、 such as text boxes or images。'),
('esc','cell navigation','exit the floating shape navigation and return to the normal navigation。'),
('ctrl＋shift、 then scroll your mouse wheel up to go left、 down to go right','cell navigation','scroll horizontally。'),
('ctrl＋alt＋equal sign （ = ）','cell navigation','zoom in。'),
('ctrl＋alt＋minus sign （ー）','cell navigation',' zoom out。'),
('ctrl＋1','cell formatting','open the format cells dialog box。'),
('ctrl＋shift＋f or ctrl＋shift＋p','cell formatting','format fonts in the format cells dialog box。'),
('f2','cell formatting','edit the active cell and put the insertion point at the end of its contents。 or、 if editing is turned off for the cell、 move the insertion point into the formula bar。 if editing a formula、 toggle point mode off or on so you can use the arrow keys to create a reference。'),
('shift＋f2','cell formatting','insert a note。'),
('shift＋f2','cell formatting','open and edit a cell note。'),
('ctrl＋shift＋f2','cell formatting','insert a threaded comment。'),
('ctrl＋shift＋f2','cell formatting','open and reply to a threaded comment。'),
('ctrl＋shift＋plus sign （＋）','cell formatting','open the insert dialog box to insert blank cells。'),
('ctrl＋minus sign （ー）','cell formatting','open the delete dialog box to delete selected cells。'),
('ctrl＋shift＋colon （：）','cell formatting','enter the current time。'),
('ctrl＋semicolon （;）','cell formatting','enter the current date。'),
('ctrl＋grave accent （`）','cell formatting','switch between displaying cell values or formulas in the worksheet。'),
('ctrl＋apostrophe （’）','cell formatting','copy a formula from the cell above the active cell into the cell or the formula bar。'),
('ctrl＋x','cell formatting','move the selected cells。'),
('ctrl＋c','cell formatting','copy the selected cells。'),
('ctrl＋v','cell formatting','paste content at the insertion point、 replacing any selection。'),
('ctrl＋alt＋v','cell formatting','open the paste special dialog box。'),
('ctrl＋i or ctrl＋3','cell formatting','italicize text or remove italic formatting。'),
('ctrl＋b or ctrl＋2','cell formatting','bold text or remove bold formatting。'),
('ctrl＋u or ctrl＋4','cell formatting','underline text or remove underline。'),
('ctrl＋5','cell formatting','apply or remove strikethrough formatting。'),
('ctrl＋6','cell formatting','switch between hiding objects、 displaying objects、 and displaying placeholders for objects。'),
('ctrl＋shift＋ampersand sign （&）','cell formatting','apply an outline border to the selected cells。'),
('ctrl＋shift＋underscore （_）','cell formatting','remove the outline border from the selected cells。'),
('ctrl＋8','cell formatting','display or hide the outline symbols。'),
('ctrl＋d','cell formatting','use the fill down command to copy the contents and format of the topmost cell of a selected range into the cells below。'),
('ctrl＋shift＋tilde sign （~）','cell formatting','apply the general number format。'),
('ctrl＋shift＋dollar sign （$）','cell formatting','apply the currency format with two decimal places （negative numbers in parentheses）。'),
('ctrl＋shift＋percent sign （%）','cell formatting','apply the percentage format with no decimal places。'),
('ctrl＋shift＋caret sign （^）','cell formatting','apply the scientific number format with two decimal places。'),
('ctrl＋shift＋number sign （#）','cell formatting','apply the date format with the day、 month、 and year。'),
('ctrl＋shift＋at sign （@）','cell formatting','apply the time format with the hour and minute、 and am or pm。'),
('ctrl＋shift＋exclamation point （！）','cell formatting','apply the number format with two decimal places、 thousands separator、 and minus sign （ー） for negative values。'),
('ctrl＋k','cell formatting','open the insert hyperlink dialog box。'),
('f7','cell formatting','check spelling in the active worksheet or selected range。'),
('ctrl＋q','cell formatting','display the quick analysis options for selected cells that contain data。'),
('ctrl＋l or ctrl＋t','cell formatting','display the create table dialog box。'),
('ctrl＋shift＋g','cell formatting','open the workbook statistics dialog box。'),
('a','paste special','paste all cell contents and formatting。'),
('f','paste special','paste only the formulas as entered in the formula bar。'),
('v','paste special','paste only the values （not the formulas）。'),
('t','paste special','paste only the copied formatting。'),
('c','paste special','paste only comments and notes attached to the cell。'),
('n','paste special','paste only the data validation settings from copied cells。'),
('h','paste special','paste all cell contents and formatting from copied cells。'),
('x','paste special','paste all cell contents without borders。'),
('w','paste special','paste only column widths from copied cells。'),
('r','paste special','paste only formulas and number formats from copied cells。'),
('u','paste special','paste only the values （not formulas） and number formats from copied cells。'),
('ctrl＋a or ctrl＋shift＋spacebar','selections performing actions','select the entire worksheet。'),
('ctrl＋shift＋page down','selections performing actions','select the current and next sheet in a workbook。'),
('ctrl＋shift＋page up','selections performing actions','select the current and previous sheet in a workbook。'),
('shift＋arrow key','selections performing actions','extend the selection of cells by one cell。'),
('ctrl＋shift＋arrow key','selections performing actions','extend the selection of cells to the last nonblank cell in the same column or row as the active cell、 or if the next cell is blank、 to the next nonblank cell。'),
('f8','selections performing actions','turn extend mode on and use the arrow keys to extend a selection。 press again to turn off。'),
('shift＋f8','selections performing actions','add a nonーadjacent cell or range to a selection of cells by using the arrow keys。'),
('alt＋enter','selections performing actions','start a new line in the same cell。'),
('ctrl＋enter','selections performing actions','fill the selected cell range with the current entry。'),
('shift＋enter','selections performing actions','complete a cell entry and select the cell above。'),
('ctrl＋spacebar','selections performing actions','select an entire column in a worksheet。'),
('shift＋spacebar','selections performing actions','select an entire row in a worksheet。'),
('ctrl＋shift＋spacebar','selections performing actions','select all objects on a worksheet when an object is selected。'),
('ctrl＋shift＋home','selections performing actions','extend the selection of cells to the beginning of the worksheet。'),
('ctrl＋a or ctrl＋shift＋spacebar','selections performing actions','select the current region if the worksheet contains data。 press a second time to select the current region and its summary rows。 press a third time to select the entire worksheet。'),
('ctrl＋shift＋asterisk sign （*）','selections performing actions','select the current region around the active cell。'),
('home','selections performing actions','select the first command on the menu when a menu or submenu is visible。'),
('ctrl＋y','selections performing actions','repeat the last command or action、 if possible。'),
('ctrl＋z','selections performing actions','undo the last action。'),
('while hovering over the collapsed items、 press and hold the shift key and scroll down。','selections performing actions','expand grouped rows or columns。'),
('while hovering over the expanded items、 press and hold the shift key and scroll up。','selections performing actions','collapse grouped rows or columns。'),
('ctrl＋alt＋p','data functions and formula bar','turn on or off tooltips for checking formulas directly in the formula bar or in the cell you’re editing。'),
('f2','data functions and formula bar','edit the active cell and put the insertion point at the end of its contents 。 or、 if editing is turned off for the cell、 move the insertion point into the formula bar。 if editing a formula 、 toggle point mode off or on so you can use the arrow keys to create a reference。'),
('ctrl＋shift＋u','data functions and formula bar','expand or collapse the formula bar。'),
('esc','data functions and formula bar','cancel an entry in the cell or formula bar。'),
('enter','data functions and formula bar','complete an entry in the formula bar and select the cell below。'),
('ctrl＋end','data functions and formula bar','move the cursor to the end of the text when in the formula bar。'),
('ctrl＋shift＋end','data functions and formula bar','select all text in the formula bar from the cursor position to the end。'),
('f9','data functions and formula bar','calculate all worksheets in all open workbooks。'),
('shift＋f9','data functions and formula bar','calculate the active worksheet。'),
('ctrl＋alt＋f9','data functions and formula bar','calculate all worksheets in all open workbooks、 regardless of whether they have changed since the last calculation。'),
('ctrl＋alt＋shift＋f9','data functions and formula bar','check dependent formulas、 and then calculate all cells in all open workbooks、 including cells not marked as needing to be calculated。'),
('alt＋shift＋f10','data functions and formula bar','display the menu or message for an error checking button。'),
('ctrl＋a','data functions and formula bar','display the function arguments dialog box when the insertion point is to the right of a function name in a formula。'),
('ctrl＋shift＋a','data functions and formula bar','insert argument names and parentheses when the insertion point is to the right of a function name in a formula。'),
('alt＋equal sign （ = ）','data functions and formula bar','insert the autosum formula'),
('ctrl＋e','data functions and formula bar','invoke flash fill to automatically recognize patterns in adjacent columns and fill the current column'),
('f4','data functions and formula bar','cycle through all combinations of absolute and relative references in a formula if a cell reference or range is selected。'),
('shift＋f3','data functions and formula bar','insert a function。'),
('ctrl＋shift＋straight quotation mark （”）','data functions and formula bar','copy the value from the cell above the active cell into the cell or the formula bar。'),
('alt＋f1','data functions and formula bar','create an embedded chart of the data in the current range。'),
('f11','data functions and formula bar','create a chart of the data in the current range in a separate chart sheet。'),
('alt＋m、 m、 d','data functions and formula bar','define a name to use in references。'),
('f3','data functions and formula bar','paste a name from the paste name dialog box （if names have been defined in the workbook）。'),
('enter','data functions and formula bar','move to the first field in the next record of a data form。'),
('alt＋f8','data functions and formula bar','create、 run、 edit、 or delete a macro。'),
('alt＋f11 ','data functions and formula bar','open the microsoft visual basic for applications editor。'),
('alt＋f12','data functions and formula bar','open the power query editor'),
('esc','refresh external data','stop a refresh operation。'),
('ctrl＋f5','refresh external data','refresh data in the current worksheet。'),
('ctrl＋alt＋f5','refresh external data','refresh all data in the workbook。'),
('shift＋f10','power pivot','open the context menu for the selected cell、 column、 or row。'),
('ctrl＋a','power pivot','select the entire table。'),
('ctrl＋c','power pivot','copy selected data。'),
('ctrl＋d','power pivot','delete the table。'),
('ctrl＋m','power pivot','move the table。'),
('ctrl＋r','power pivot','rename the table。'),
('ctrl＋s','power pivot','save the file。'),
('ctrl＋y','power pivot','redo the last action。'),
('ctrl＋z','power pivot','undo the last action。'),
('ctrl＋spacebar','power pivot','select the current column。'),
('shift＋spacebar','power pivot','select the current row。'),
('shift＋page down','power pivot','select all cells from the current location to the last cell of the column。'),
('shift＋page up','power pivot','select all cells from the current location to the first cell of the column。'),
('shift＋end','power pivot','select all cells from the current location to the last cell of the row。'),
('shift＋home','power pivot','select all cells from the current location to the first cell of the row。'),
('ctrl＋page up','power pivot','move to the previous table。'),
('ctrl＋page down','power pivot','move to the next table。'),
('ctrl＋home','power pivot','move to the first cell in the upperーleft corner of selected table。'),
('ctrl＋end','power pivot','move to the last cell in the lowerーright corner of selected table。'),
('ctrl＋left arrow key','power pivot','move to the first cell of the selected row。'),
('ctrl＋right arrow key','power pivot','move to the last cell of the selected row。'),
('ctrl＋up arrow key','power pivot','move to the first cell of the selected column。'),
('ctrl＋down arrow key','power pivot','move to the last cell of selected column。'),
('ctrl＋esc','power pivot','close a dialog box or cancel a process、 such as a paste operation。'),
('alt＋down arrow key','power pivot','open the autofilter menu dialog box。'),
('f5','power pivot','open the go to dialog box。'),
('f9','power pivot','recalculate all formulas in the power pivot window。 for more information、 see recalculate formulas in power pivot。'),
('f1','function keys','displays the excel help task pane。'),
('ctrl＋f1','function keys','displays or hides the ribbon。'),
('alt＋f1','function keys','creates an embedded chart of the data in the current range。'),
('alt＋shift＋f1','function keys','inserts a new worksheet。'),
('ctrl＋shift＋f1','function keys','toggles full screen mode'),
('f2','function keys','edit the active cell and put the insertion point at the end of its contents。 or、 if editing is turned off for the cell、 move the insertion point into the formula bar。 if editing a formula、 toggle point mode off or on so you can use the arrow keys to create a reference。'),
('shift＋f2','function keys','adds or edits a cell note。'),
('ctrl＋f2','function keys','displays the print preview area on the print tab in the backstage view。'),
('f3','function keys','displays the paste name dialog box。 available only if names have been defined in the workbook。'),
('shift＋f3','function keys','displays the insert function dialog box。'),
('f4','function keys','repeats the last command or action、 if possible。'),
('f4','function keys','when a cell reference or range is selected in a formula、 f4 cycles through all the various combinations of absolute and relative references。'),
('ctrl＋f4','function keys','closes the selected workbook window。'),
('alt＋f4','function keys','closes excel。'),
('f5','function keys','displays the go to dialog box。'),
('ctrl＋f5','function keys','restores the window size of the selected workbook window。'),
('f6','function keys','switches between the worksheet、 ribbon、 task pane、 and zoom controls。 in a worksheet that has been split、 f6 includes the split panes when switching between panes and the ribbon area。'),
('shift＋f6','function keys','switches between the worksheet、 zoom controls、 task pane、 and ribbon。'),
('ctrl＋f6','function keys','switches between two excel windows。'),
('ctrl＋shift＋f6','function keys','switches between all excel windows。'),
('f7','function keys','opens the spelling dialog box to check spelling in the active worksheet or selected range。'),
('ctrl＋f7','function keys','performs the move command on the workbook window when it is not maximized。 use the arrow keys to move the window、 and when finished press enter、 or esc to cancel。'),
('f8','function keys','turns extend mode on or off。 in extend mode、 extended selection appears in the status line 、 and the arrow keys extend the selection。'),
('shift＋f8','function keys','enables you to add a nonーadjacent cell or range to a selection of cells by using the arrow keys。'),
('ctrl＋f8','function keys','performs the size command when a workbook is not maximized。'),
('alt＋f8','function keys','displays the macro dialog box to create、 run、 edit、 or delete a macro。'),
('f9','function keys','calculates all worksheets in all open workbooks。'),
('shift＋f9','function keys','calculates the active worksheet。'),
('ctrl＋alt＋f9','function keys','calculates all worksheets in all open workbooks、 regardless of whether they have changed since the last calculation。'),
('ctrl＋alt＋shift＋f9','function keys','rechecks dependent formulas、 and then calculates all cells in all open workbooks、 including cells not marked as needing to be calculated。'),
('ctrl＋f9','function keys','minimizes a workbook window to an icon。'),
('f10','function keys','turns key tips on or off。 （pressing alt does the same thing。）'),
('shift＋f10','function keys','displays the context menu for a selected item。'),
('alt＋shift＋f10','function keys','displays the menu or message for an error checking button。'),
('ctrl＋f10','function keys','maximizes or restores the selected workbook window。'),
('f11','function keys','creates a chart of the data in the current range in a separate chart sheet。'),
('shift＋f11','function keys','inserts a new worksheet。'),
('alt＋f11','function keys','opens the microsoft visual basic for applications editor、 in which you can create a macro by using visual basic for applications （vba）。'),
('f12','function keys','displays the save as dialog box。'),
('alt','more keys','displays the key tips （new shortcuts） on the ribbon。'),
('alt、 w、 p','more keys','switches the worksheet to page layout view。'),
('alt、 w、 l','more keys','switches the worksheet to normal view。'),
('alt、 w、 i','more keys','switches the worksheet to page break preview view。'),
('arrow key','more keys','move one cell up、 down、 left、 or right in a worksheet。'),
('ctrl＋arrow key','more keys','moves to the edge of the current data region in a worksheet。'),
('shift＋arrow key','more keys','extends the selection of cells by one cell。'),
('ctrl＋shift＋arrow key','more keys','extends the selection of cells to the last nonblank cell in the same column or row as the active cell、 or if the next cell is blank、 extends the selection to the next nonblank cell。'),
('left or right arrow key','more keys','selects the tab to the left or right when the ribbon is selected。 when a submenu is open or selected、 these arrow keys switch between the main menu and the submenu。 when a ribbon tab is selected、 these keys navigate the tab buttons。'),
('down or up arrow key','more keys','selects the next or previous command when a menu or submenu is open。 when a ribbon tab is selected、 these keys navigate up or down the tab group。'),
('arrow key','more keys','in a dialog box、 arrow keys move between options in an open dropーdown list、 or between options in a group of options。'),
('down or alt＋down arrow key','more keys','opens a selected dropーdown list。'),
('backspace','more keys','deletes one character to the left in the formula bar。'),
('backspace','more keys','clears the content of the active cell。'),
('backspace','more keys','in cell editing mode、 it deletes the character to the left of the insertion point。'),
('delete','more keys',' removes the cell contents （data and formulas） from selected cells without affecting cell formats、 threaded comments、 or notes。'),
('delete','more keys',' in cell editing mode、 it deletes the character to the right of the insertion point。'),
('end','more keys',' end turns end mode on or off。 in end mode、 you can press an arrow key to move to the next nonblank cell in the same column or row as the active cell。 end mode turns off automatically after pressing the arrow key。 make sure to press end again before pressing the next arrow key。 end mode is shown in the status bar when it is on。'),
('end','more keys','if the cells are blank、 pressing end followed by an arrow key moves to the last cell in the row or column。'),
('end','more keys','also selects the last command on the menu when a menu or submenu is visible。'),
('ctrl＋end','more keys','moves to the last cell on a worksheet、 to the lowest used row of the rightmost used column。 if the cursor is in the formula bar、 ctrl＋end moves the cursor to the end of the text。'),
('ctrl＋shift＋end','more keys',' extends the selection of cells to the last used cell on the worksheet （lowerーright corner）。 if the cursor is in the formula bar、 ctrl＋shift＋end selects all text in the formula bar from the cursor position to the end—this does not affect the height of the formula bar。'),
('enter','more keys','completes a cell entry from the cell or the formula bar and selects the cell below （by default）。'),
('enter','more keys','in a data form、 it moves to the first field in the next record。'),
('enter','more keys','opens a selected menu （press f10 to activate the menu bar） or performs the action for a selected command。'),
('enter','more keys','in a dialog box、 it performs the action for the default command button in the dialog box （the button with the bold outline、 often the ok button）。'),
('alt＋enter','more keys','starts a new line in the same cell。'),
('ctrl＋enter','more keys','fills the selected cell range with the current entry。'),
('shift＋enter','more keys','completes a cell entry and selects the cell above。'),
('end','more keys','cancels an entry in the cell or formula bar。'),
('end','more keys','closes an open menu or submenu、 dialog box、 or message window。'),
('end','more keys','moves to the beginning of a row in a worksheet。'),
('home','more keys','moves to the cell in the upperーleft corner of the window when scroll lock is turned on。'),
('home','more keys','selects the first command on the menu when a menu or submenu is visible。'),
('ctrl＋home','more keys','moves to the beginning of a worksheet。'),
('ctrl＋shift＋home','more keys','extends the selection of cells to the beginning of the worksheet。'),
('page up','more keys','moves one screen down in a worksheet。'),
('alt＋page','more keys','down moves one screen to the right in a worksheet。'),
('ctrl＋page','more keys','down moves to the next sheet in a workbook。'),
('ctrl＋shift＋page','more keys','down selects the current and next sheet in a workbook。'),
('page down','more keys','moves one screen up in a worksheet。'),
('alt＋page','more keys','up moves one screen to the left in a worksheet。'),
('ctrl＋page','more keys','up moves to the previous sheet in a workbook。'),
('ctrl＋shift＋page','more keys','up selects the current and previous sheet in a workbook。'),
('shift','more keys','hold the shift key while you drag a selected row、 column、 or selected cells to move the selected cells and drop to insert them in a new location。'),
('shift','more keys','in a dialog box、 performs the action for the selected button、 or selects or clears a checkbox。'),
('ctrl＋spacebar','more keys','selects an entire column in a worksheet。'),
('shift＋spacebar','more keys','selects an entire row in a worksheet。'),
('ctrl＋shift＋spacebar','more keys','selects the entire worksheet。'),
('ctrl＋shift＋spacebar ','more keys','if the worksheet contains data、 selects the current region。 pressing ctrl＋shift＋spacebar a second time selects the current region and its summary rows。 pressing ctrl＋shift＋spacebar a third time selects the entire worksheet。'),
('ctrl＋shift＋spacebar','more keys','when an object is selected、 selects all objects on a worksheet。'),
('alt＋spacebar','more keys','displays the control menu for the excel window。'),
('tab','more keys','moves one cell to the right in a worksheet。'),
('tab','more keys','moves between unlocked cells in a protected worksheet。'),
('tab','more keys','moves to the next option or option group in a dialog box。'),
('shift＋tab','more keys','moves to the previous cell in a worksheet or the previous option in a dialog box。'),
('ctrl＋tab','more keys','switches to the next tab in a dialog box、 or （if no dialog box is open） switches between two excel windows。 '),
('ctrl＋shift＋tab','more keys','switches to the previous tab in a dialog box、 or （if no dialog box is open） switches between all excel windows。'),
('alt ＋ h ＋ m ＋ a','motions','unmerge cells'),
('alt ＋ h ＋ m ＋ c','motions','merge cells and center align');

