DROP TABLE IF EXISTS powerpointshortcuts;

CREATE TABLE powerpointshortcuts(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
	shortcut VARCHAR(40),
	category VARCHAR(175),
	extension TEXT
);

INSERT INTO powerpointshortcuts(shortcut,category,extension)
VALUES
('shortcut','category','extension'),
('Create new presentation。','Ctrl＋N','Frequently Used Shortcuts'),
('Add a new slide。','Ctrl＋M','Frequently Used Shortcuts'),
('Apply bold formatting to the selected text。','Ctrl＋B','Frequently Used Shortcuts'),
('Open the Font dialog box。','Ctrl＋T','Frequently Used Shortcuts'),
('Cut selected text、 object、 or slide。','Ctrl＋X','Frequently Used Shortcuts'),
('Copy selected text、 object、 or slide。','Ctrl＋C','Frequently Used Shortcuts'),
('Paste cut or copied text、 object、 or slide。','Ctrl＋V','Frequently Used Shortcuts'),
('Insert a hyperlink。','Ctrl＋K','Frequently Used Shortcuts'),
('Insert a new comment。','Ctrl＋Alt＋M','Frequently Used Shortcuts'),
('Undo the last action。','Ctrl＋Z','Frequently Used Shortcuts'),
('Redo the last action。','Ctrl＋Y','Frequently Used Shortcuts'),
('Go to the next slide。','Page down','Frequently Used Shortcuts'),
('Go to the previous slide。','Page up','Frequently Used Shortcuts'),
('Start the slide show。','F5','Frequently Used Shortcuts'),
('End the slide show。','Esc','Frequently Used Shortcuts'),
('Print a presentation。','Ctrl＋P','Frequently Used Shortcuts'),
('Save the presentation。','Ctrl＋S','Frequently Used Shortcuts'),
('Close PowerPoint。','Ctrl＋Q','Frequently Used Shortcuts'),
('Insert a new slide。','Ctrl＋M','Word with presentations and slides'),
('Go to the next slide。','Page down','Word with presentations and slides'),
('Go to the previous slide。','Page up','Word with presentations and slides'),
('Zoom out。','Ctrl＋Minus sign （ー）','Word with presentations and slides'),
('Zoom in。','Ctrl＋Plus sign （＋）','Word with presentations and slides'),
('Zoom to fit。','Ctrl＋Alt＋O','Word with presentations and slides'),
('Make a copy of the selected slide。','Ctrl＋Shift＋D','Word with presentations and slides'),
('Open a presentation。','Ctrl＋O','Word with presentations and slides'),
('Close a presentation。','Ctrl＋D','Word with presentations and slides'),
('Save a presentation with a different name、 location、 or file format。','Ctrl＋Shift＋S','Word with presentations and slides'),
('Cancel a command、 such as Save As。','Esc','Word with presentations and slides'),
('Open a recent file。','Ctrl＋O','Word with presentations and slides'),
('Cut selected object or text。','Ctrl＋X','Word with objects and text'),
('Copy selected object or text。','Ctrl＋C','Word with objects and text'),
('Paste cut or copied object or text。','Ctrl＋V','Word with objects and text'),
('Duplicate selected objects。','Ctrl＋D or Ctrl＋Drag the mouse','Word with objects and text'),
('Duplicate selected objects。','Ctrl＋D or Ctrl＋Drag the mouse','Word with objects and text'),
('Duplicate selected objects。','Office 2010 and Office 2007： Not available','Word with objects and text'),
('Copy the formatting of the selected object or text。','Ctrl＋Shift＋C','Word with objects and text'),
('Paste copied formatting to the selected object or text。','Ctrl＋Shift＋V','Word with objects and text'),
('Copy animation painter。','Alt＋Shift＋C','Word with objects and text'),
('Copy animation painter。','Alt＋Shift＋C','Word with objects and text'),
('Copy animation painter。','Office 2010 and Office 2007： Not available','Word with objects and text'),
('Paste animation painter。','Alt＋Shift＋V','Word with objects and text'),
('Paste animation painter。','Alt＋Shift＋V','Word with objects and text'),
('Paste animation painter。','Office 2010 and Office 2007： Not available','Word with objects and text'),
('Open the Paste Special dialog box。','Ctrl＋Alt＋V','Word with objects and text'),
('Select one character to the right。','Shift＋Right arrow key','Select Text'),
('Select one character to the left。','Shift＋Left arrow key','Select Text'),
('Select to the end of a word。','Ctrl＋Shift＋Right arrow key','Select Text'),
('Select to the beginning of a word。','Ctrl＋Shift＋Left arrow key','Select Text'),
('Select from the insertion point to the same point one line up。','Shift＋Up arrow key','Select Text'),
('Select from the insertion point to the same point one line down。','Shift＋Down arrow key','Select Text'),
('Select from the insertion point to the end of the paragraph。','Ctrl＋Shift＋Down ','Select Text'),
('Select from the insertion point to the end of the paragraph。','arrow key','Select Text'),
('Select from the insertion point to the beginning of the paragraph。','Ctrl＋Shift＋Up arrow key','Select Text'),
('Select text within an object （with an object selected）。','Enter','Select Text'),
('Select an object when the text inside the object is selected。','Esc','Select Text'),
('Delete one character to the left。','Backspace','Delete Text'),
('Delete one word to the left。','Ctrl＋Backspace','Delete Text'),
('Delete one character to the right。','Delete','Delete Text'),
('Delete one word to the right （with the cursor between the words）。','Ctrl＋Delete','Delete Text'),
('Move one character to the left。','Left arrow key','Move Around In Text'),
('Move one character to the right。','Right arrow key','Move Around In Text'),
('Move one line up。','Up arrow key','Move Around In Text'),
('Move one line down。','Down arrow key','Move Around In Text'),
('Move one word to the left。','Ctrl＋Left arrow key','Move Around In Text'),
('Move one word to the right。','Ctrl＋Right arrow key','Move Around In Text'),
('Move to the end of a line。','End','Move Around In Text'),
('Move to the beginning of a line。','Home','Move Around In Text'),
('Move up one paragraph。','Ctrl＋Up arrow key','Move Around In Text'),
('Move down one paragraph。','Ctrl＋Down arrow key','Move Around In Text'),
('Move to the end of a text box。','Ctrl＋End','Move Around In Text'),
('Move to the beginning of a text box。','Ctrl＋Home','Move Around In Text'),
('Move to the next title or body text placeholder。 If it is the last placeholder on a slide、 this action inserts a new slide with the same slide layout as the original slide。','Ctrl＋Enter','Move Around In Text'),
('Promote a paragraph。','Alt＋Shift＋Left arrow key','Move Around In Text'),
('Demote a paragraph。','Alt＋Shift＋Right arrow key','Move Around In Text'),
('Move selected paragraphs up。','Alt＋Shift＋Up arrow key','Move Around In Text'),
('Move selected paragraphs down。','Alt＋Shift＋Down arrow key','Move Around In Text'),
('Open the Find dialog box。','Ctrl＋F','Find and replace text'),
('Open the Replace dialog box。','Ctrl＋H','Find and replace text'),
('Repeat the last Find action。','Shift＋F4','Find and replace text'),
('Open the Font dialog box。','Ctrl＋T or Ctrl＋Shift＋F','Format text'),
('Increase the font size。','Ctrl＋Shift＋Right angle bracket （>）','Format text'),
('Decrease the font size。','Ctrl＋Shift＋Left angle bracket （<）','Format text'),
('Switch between sentence case、 lowercase、 or uppercase。','Shift＋F3','Format text'),
('Apply bold formatting。','Ctrl＋B','Format text'),
('Apply underline formatting。','Ctrl＋U','Format text'),
('Apply italic formatting。','Ctrl＋I','Format text'),
('Apply subscript formatting （automatic spacing）。','Ctrl＋Equal sign （ = ）','Format text'),
('Apply superscript formatting （automatic spacing）。','Ctrl＋Shift＋Plus sign （＋）','Format text'),
('Remove manual character formatting、 such as subscript and superscript。','Ctrl＋Spacebar','Format text'),
('Center a paragraph。','Ctrl＋E','Format text'),
('Justify a paragraph。','Ctrl＋J','Format text'),
('Left align a paragraph。','Ctrl＋L','Format text'),
('Right align a paragraph。','Ctrl＋R','Format text'),
('Create Bullet List','1。 Do one of the following：To create a list that uses filled round bullets、 press the Asterisk sign （*）。To create a list that uses hyphens、 press the Minus sign （ー）。To create a list that uses arrow bullets、 press the Right angle bracket （>）。To create a list that uses diamonds、 press Left angle bracket （<） ＋ Right angle bracket （>）。To create a list that uses arrows、 press two minus signs （ー） ＋ Right angle bracket （>）。To create a list that uses double arrows、 press the Equal sign （ = ） ＋ Right angle bracket （>）。 2。 Press Spacebar。 3。 Type the list item、 and then press Enter。','Create List'),
('Move to the next cell。','Tab key','Work With Tables'),
('Move to the preceding cell。','Shift＋Tab','Work With Tables'),
('Move to the next row。','Down arrow key','Work With Tables'),
('Move to the preceding row。','Up arrow key','Work With Tables'),
('Insert a tab in a cell。','Ctrl＋Tab','Work With Tables'),
('Start a new paragraph。','Enter','Work With Tables'),
('Add a new row at the bottom of the table with the cursor in the last cell of the last row。','Tab key','Work With Tables'),
('Move the selected slide or section up in order。','Ctrl＋Up arrow key','Move a slide'),
('Move the selected slide or section down in order。','Ctrl＋Down arrow key','Move a slide'),
('Move the selected slide or section to the beginning。','Ctrl＋Shift＋Up arrow key','Move a slide'),
('Move the selected slide or section to the end。','Ctrl＋Shift＋Down arrow key','Move a slide'),
('Switch to Presenter view。','Alt＋F5','Work with views and panes'),
('Switch to Slide Show。','F5','Work with views and panes'),
('Toggle between Outline and Thumbnail views。','Ctrl＋Shift＋Tab','Work with views and panes'),
('Switch to full screen （hide menus）。','Ctrl＋F1','Work with views and panes'),
('Show or hide guides。','Alt＋F9','Work with views and panes'),
('Show or hide the grid。','Shift＋F9','Work with views and panes'),
('Cycle clockwise through panes in the Normal view。','F6','Work with views and panes'),
('Cycle counterclockwise through panes in the Normal view。','Shift＋F6','Work with views and panes'),
('Switch between the Thumbnail pane and the Outline View pane。','Ctrl＋Shift＋Tab','Work with views and panes'),
('Show Outline View level 1 headings。','Alt＋Shift＋1','Work with views and panes'),
('Expand Outline View text below a heading。','Alt＋Shift＋Plus sign （＋）','Work with views and panes'),
('Collapse Outline View text below a heading。','Alt＋Shift＋Minus sign （ー）','Work with views and panes'),
('Select all text in the Outline View。','Ctrl＋A','Work with views and panes'),
('Select all slides in the Slide Sorter view or the thumbnail pane。','Ctrl＋A','Work with views and panes'),
('Show the help menu。','F1','Work with views and panes'),
('Open the Selection pane。','Alt＋F10','Work with the Selection pane'),
('Open the Selection pane。','Alt＋H、 S、 L、 P','Work with the Selection pane'),
('Open the Selection pane。','Office 2007： Alt＋J、 D、 A、 P','Work with the Selection pane'),
('Cycle the focus through the different panes。','F6','Work with the Selection pane'),
('Display the context menu。','Shift＋F10 or the Windows Menu key','Work with the Selection pane'),
('Move the focus to a single item or group。','Up or Down arrow key','Work with the Selection pane'),
('Move the focus from an item in a group to its parent group。','Left arrow key','Work with the Selection pane'),
('Move the focus from a group to the first item in that group。','Right arrow key','Work with the Selection pane'),
('Expand a focused group and all its child groups。','Asterisk sign （*） （on numeric keypad only）','Work with the Selection pane'),
('Expand a focused group。','Plus sign （＋） （on numeric keypad only） or Right arrow key','Work with the Selection pane'),
('Collapse a focused group。','Minus sign （ー） （on numeric keypad only） or Left arrow key','Work with the Selection pane'),
('Move the focus to an item and select it。','Shift＋Up or Down arrow key','Work with the Selection pane'),
('Select a focused item。','Spacebar or Enter','Work with the Selection pane'),
('Cancel selection of a focused item。','Shift＋Spacebar or Shift＋Enter','Work with the Selection pane'),
('Move a selected item forward。','Ctrl＋Shift＋F','Work with the Selection pane'),
('Move a selected item backward。','Ctrl＋Shift＋B','Work with the Selection pane'),
('Show or hide a focused item。','Ctrl＋Shift＋S','Work with the Selection pane'),
('Rename a focused item。','F2','Work with the Selection pane'),
('Switch the keyboard focus within the Selection pane between tree view and the Show All and Hide All buttons。','Tab key or Shift＋Tab','Work with the Selection pane'),
('Collapse all groups （with the focus in the tree view of the Selection pane）。','Alt＋Shift＋1','Work with the Selection pane'),
('Expand all groups。','Alt＋Shift＋9','Work with the Selection pane'),
('Move to a task pane from another pane or area in the program window。 （You might need to press F6 more than once。）','F6','Work with the task pane'),
('When a task pane option has focus、 move to the next or previous option in the task pane。','Tab key or Shift＋Tab','Work with the task pane'),
('Display the full set of commands on a task pane menu。 You can access、 for example、 the Close、 Move、 or Size buttons of a task pane。','Ctrl＋Spacebar','Work with the task pane'),
('Display the full set of commands on a task pane menu。 You can access、 for example、 the Close、 Move、 or Size buttons of a task pane。','Ctrl＋Spacebar','Work with the task pane'),
('Display the full set of commands on a task pane menu。 You can access、 for example、 the Close、 Move、 or Size buttons of a task pane。','Office 2010： Ctrl＋Down arrow key','Work with the task pane'),
('Move to the next command on the task pane menu。','Up and Down arrow keys','Work with the task pane'),
('Select the highlighted option on the task pane menu。','Enter','Work with the task pane'),
('Move or resize the task pane after the corresponding command has been selected。','Arrow keys','Work with the task pane'),
('Close a task pane。','Ctrl＋Spacebar、 C','Work with the task pane'),
('Move to the Tell me or Search field on the ribbon and type a search term for assistance or Help content。','Alt＋Q、 then type the search term。','Open the ribbon tabs'),
('Open the File menu。','Alt＋F','Open the ribbon tabs'),
('Open the Home tab and format slides、 fonts、 paragraphs、 or drawings。','Alt＋H','Open the ribbon tabs'),
('Open the Insert tab and insert slides、 tables、 images、 illustrations、 forms、 links、 text、 symbols、 or media。','Alt＋N','Open the ribbon tabs'),
('Open the Draw tab and access the drawing tools。','Alt＋J、 I','Open the ribbon tabs'),
('Open the Design tab and apply themes and customize slides。','Alt＋G','Open the ribbon tabs'),
('Open the Transitions tab and add transitions between slides。','Alt＋K','Open the ribbon tabs'),
('Open the Animations tab and add animations to slides。','Alt＋A','Open the ribbon tabs'),
('Open the Slide Show tab and set up and play the slide show。','Alt＋S','Open the ribbon tabs'),
('Open the Review tab and check spelling and accessibility and add comments。','Alt＋R','Open the ribbon tabs'),
('Open the View tab and preview presentation layouts、 show and hide gridlines and guides、 set zoom magnification、 manage windows、 and view macros。','Alt＋W','Open the ribbon tabs'),
('Open the Recording tab and manage screen recordings、 audio、 and video in your presentation。','Alt＋C','Open the ribbon tabs'),
('Open the Help tab and browse the PowerPoint、 contact support、 and leave feedback。','Alt＋Y、 2','Open the ribbon tabs'),
('Select the active tab on the ribbon、 and activate the access keys。','Alt or F10。 To move to a different tab、 use access keys or the arrow keys。','Work in the ribbon with the keyboard'),
('Move the focus to commands on the ribbon。','Tab key or Shift＋Tab','Work in the ribbon with the keyboard'),
('Move down、 up、 left、 or right、 respectively、 among the items on the ribbon。','Arrow keys','Work in the ribbon with the keyboard'),
('Show the tooltip for the ribbon element currently in focus。','Ctrl＋Shift＋F10','Work in the ribbon with the keyboard'),
('Activate a selected button or control。','Spacebar or Enter','Work in the ribbon with the keyboard'),
('Open the list for a selected command。','Down arrow key','Work in the ribbon with the keyboard'),
('Open the menu for a selected button。','Alt＋Down arrow key','Work in the ribbon with the keyboard'),
('When a menu or submenu is open、 move to the next command。','Down arrow key','Work in the ribbon with the keyboard'),
('Expand or collapse the ribbon。','Ctrl＋F1','Work in the ribbon with the keyboard'),
('Open a context menu。','Shift＋F10 or the Windows Menu key','Work in the ribbon with the keyboard'),
('Move to the submenu when a main menu is open or selected。','Left arrow key','Work in the ribbon with the keyboard'),
('Get help on the currently selected command or control on the ribbon。','F1','Work in the ribbon with the keyboard'),
('Change the font size for selected text。','Alt＋H、 F、 S','Other useful ribbon keyboard shortcuts'),
('Open the Zoom dialog box。','Alt＋W、 Q','Other useful ribbon keyboard shortcuts'),
('Print all slides in your presentation as full page slides using your default printer settings （when the Print dialog box is open）。','Alt＋P、 P','Other useful ribbon keyboard shortcuts'),
('Select a theme。','Alt＋G、 H','Other useful ribbon keyboard shortcuts'),
('Select a slide layout。','Alt＋H、 L','Other useful ribbon keyboard shortcuts'),
('Show or hide the Notes pane in the Normal view。','Alt＋W、 P、 N','Other useful ribbon keyboard shortcuts'),
('Open the clipboard。','Alt＋H、 F、 O','Other useful ribbon keyboard shortcuts'),
('Insert a text box。','Alt＋N、 X','Other useful ribbon keyboard shortcuts'),
('Insert an embedded document or spreadsheet as an object。','Alt＋N、 J','Other useful ribbon keyboard shortcuts'),
('Insert WordArt。','Alt＋N、 W','Other useful ribbon keyboard shortcuts'),
('Insert a picture from your device。 ','Alt＋N、 P、 D','Other useful ribbon keyboard shortcuts'),
('Insert a shape。','Alt＋N、 S、 H','Other useful ribbon keyboard shortcuts');

