INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Microsoft Management Consoles(MSCs)', 'azman.msc', 'Used for managing authorization policies. It allows you to create and manage role-based access control.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Microsoft Management Consoles(MSCs)', 'certlm.msc', 'Displays the local machine''s certificate store. You can manage certificates for the computer.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Microsoft Management Consoles(MSCs)', 'certmgr.msc', 'Displays the user certificate store. It allows you to manage certificates for the current user.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Microsoft Management Consoles(MSCs)', 'comexp.msc', 'Opens the Component Services management console, which is used to manage COM+ applications and DCOM configuration.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Microsoft Management Consoles(MSCs)', 'compmgmt.msc', 'Opens the Computer Management console, which provides access to several system management tools, including Disk Management, Event Viewer, and Services.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Microsoft Management Consoles(MSCs)', 'devmgmt.msc', 'Opens Device Manager, which allows you to view and manage hardware devices and their drivers.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Microsoft Management Consoles(MSCs)', 'diskmgmt.msc', 'Opens Disk Management, where you can manage disk partitions, format drives, and assign drive letters.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Microsoft Management Consoles(MSCs)', 'eventvwr.msc', 'Opens Event Viewer, which allows you to view logs related to system, security, and application events.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Microsoft Management Consoles(MSCs)', 'fsmgmt.msc', 'Opens Shared Folders, where you can manage shared resources on the system, including files and sessions.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Microsoft Management Consoles(MSCs)', 'lusrmgr.msc', 'Opens Local Users and Groups, where you can manage user accounts and groups on the local machine.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Microsoft Management Consoles(MSCs)', 'perfmon.msc', 'Opens Performance Monitor, which allows you to monitor system performance metrics in real time.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Microsoft Management Consoles(MSCs)', 'services.msc', 'Opens Services, where you can manage the services running on the system, including starting and stopping services.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Microsoft Management Consoles(MSCs)', 'taskschd.msc', 'Opens Task Scheduler, which allows you to schedule tasks and automate various system operations.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Microsoft Management Consoles(MSCs)', 'tpm.msc', 'Opens the Trusted Platform Module (TPM) Management console for managing TPM hardware security features.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Microsoft Management Consoles(MSCs)', 'WF.msc', 'Opens Windows Firewall with Advanced Security, where you can configure inbound and outbound firewall rules.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Control Panel Applets(CPL)', 'appwiz.cpl', 'Opens Programs and Features, allowing you to uninstall or change installed applications.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Control Panel Applets(CPL)', 'firewall.cpl', 'Opens Windows Firewall settings, where you can configure firewall rules and exceptions.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Control Panel Applets(CPL)', 'bthprops.cpl', 'Opens Bluetooth settings, allowing you to manage Bluetooth devices and configurations.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Control Panel Applets(CPL)', 'desk.cpl', 'Opens Display settings, where you can configure screen resolution, orientation, and multiple display options.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Control Panel Applets(CPL)', 'hdwwiz.cpl', 'Opens the Add Hardware Wizard, which guides you through the process of installing new hardware.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Control Panel Applets(CPL)', 'inetcpl.cpl', 'Opens Internet Properties, where you can manage settings related to Internet Explorer and your internet connection.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Control Panel Applets(CPL)', 'intl.cpl', 'Opens Region and Language settings, allowing you to configure language, locale, and formats.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Control Panel Applets(CPL)', 'irprops.cpl', 'Opens Infrared (IR) properties, allowing you to manage infrared device settings.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Control Panel Applets(CPL)', 'joy.cpl', 'Opens Game Controllers settings, where you can manage and test connected game controllers.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Control Panel Applets(CPL)', 'main.cpl', 'Opens Mouse properties for configuring mouse settings.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Control Panel Applets(CPL)', 'mmsys.cpl', 'Opens Sound settings, where you can manage audio devices and configurations.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Control Panel Applets(CPL)', 'ncpa.cpl', 'Opens Network Connections, allowing you to manage network adapters and connections.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Control Panel Applets(CPL)', 'powercfg.cpl', 'Opens Power Options, where you can configure power plans and settings.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Control Panel Applets(CPL)', 'sysdm.cpl', 'Opens System Properties, where you can manage system settings, including hardware profiles and system protection.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Control Panel Applets(CPL)', 'telephon.cpl', 'Opens Phone and Modem settings, allowing you to manage telephony devices.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Control Panel Applets(CPL)', 'timedate.cpl', 'Opens Date and Time settings, where you can configure the system clock and time zone.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Control Panel Applets(CPL)', 'wscui.cpl', 'Opens Windows Security Center, where you can manage security settings for your system.');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Office 365', 'excel', 'Open Excel');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Office 365', 'powerpnt', 'Open Powerpoint');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Office 365', 'winword', 'Open Word');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Office 365', 'access', 'Open Access');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Office 365', 'onenote', 'Open OneNote');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Office 365', 'outlook', 'Open Outlook');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Office 365', 'msteams', 'Open Teams');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Open Browser', 'chrome', 'Open Chrome');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Open Browser', 'msedge', 'Open Edge');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Open Browser', 'brave', 'Open Brave');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'powershell ise', 'Open PowerShell ISE');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'cmd', 'Open Command Prompt');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'explorer', 'Open File Explorer');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'msinfo32', 'Open System Information');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'mspaint', 'Open Paint');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'notepad', 'Open Notepad');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'regedit', 'Open Registry Editor');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'taskmgr', 'Open Task Manager');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'winver', 'Open Windows Version Information');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'control', 'Open Control Panel');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'calc', 'Open Calculator');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'charmap', 'Open Character Map');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'cleanmgr', 'Open Disk Cleanup');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'dfrgui', 'Open Disk Defragmenter');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'dxdiag', 'Open DirectX Diagnostic Tool');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'eventvwr', 'Open Event Viewer');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'iexplore', 'Open Internet Explorer');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'magnify', 'Open Magnifier');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'msconfig', 'Open System Configuration');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'osk', 'Open On-Screen Keyboard');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'perfmon', 'Open Performance Monitor');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'snippingtool', 'Open Snipping Tool');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'stikynot', 'Open Sticky Notes');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'sysedit', 'Open System Editor');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'taskmgr', 'Open Task Manager');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'wab', 'Open Windows Address Book');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'write', 'Open WordPad');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'wscript', 'Open Windows Script Host Settings');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'wabmig', 'Open Windows Address Book Migration Tool');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES('Windows Specific', 'wabmig', 'Open Windows Address Book Migration Tool');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.AdministrativeTools','Administrative Tools');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.AutoPlay','AutoPlay');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.BackupAndRestoreCenter','Backup and Restore (Windows 7)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.BitLockerDriveEncryption','BitLocker Drive Encryption');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.ColorManagement','Color Management');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.CredentialManager','Credential Manager');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.DateAndTime','Date and Time (Date and Time)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control date/time','Date and Time (Date and Time)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.DefaultPrograms','Default Programs');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.DeviceManager','Device Manager');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.DevicesAndPrinters','Devices and Printers');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.EaseOfAccessCenter','Ease of Access Center');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.FolderOptions','File Explorer Options (General tab)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.FileHistory','File History');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.Fonts','Fonts');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.GameControllers','Game Controllers');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.GetPrograms','Get Programs');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.HomeGroup','HomeGroup');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.IndexingOptions','Indexing Options');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.Infrared','Infrared');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.InfraredOptions','Infrared');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.InternetOptions','Internet Properties (General tab)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.Keyboard','Keyboard');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.Language','Language');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.Mouse','Mouse Properties (Buttons tab 0)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.NetworkAndSharingCenter','Network and Sharing Center');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.OfflineFiles','Offline Files');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.PhoneAndModem','Phone and Modem');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.PowerOptions','Power Options');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.PowerOptions /page pageCreateNewPlan','Power Options - Create a Power Plan');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.PowerOptions /page pagePlanSettings','Power Options - Edit Plan Settings');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.PowerOptions /page pageGlobalSettings','Power Options - System Settings');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.ProgramsAndFeatures','Programs and Features');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.Recovery','Recovery');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.RegionalAndLanguageOptions /page /p:"Administrative"','Region (Administrative tab)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.RegionAndLanguage','Region (Formats tab)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.RegionalAndLanguageOptions /page /p:"Location"','Region (Location tab)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.RemoteAppAndDesktopConnections','RemoteApp and Desktop Connections');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.ScannersAndCameras','Scanners and Cameras');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.ActionCenter','Security and Maintenance');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.DefaultPrograms /page pageFileAssoc','Set Associations');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.DefaultPrograms /page pageDefaultProgram','Set Default Programs');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.Sound','Sound (Playback tab)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.SpeechRecognition','Speech Recognition');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.StorageSpaces','Storage Spaces');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.SyncCenter','Sync Center');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.System','System');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.TabletPCSettings','Tablet PC Settings');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.TextToSpeech','Text to Speech');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.UserAccounts','User Accounts');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.WindowsFirewall','Windows Defender Firewall');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.MobilityCenter','Windows Mobility Center');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands Powershell','control /name Microsoft.iSCSIInitiator','iSCSI Initiator');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.AdministrativeTools','Administrative Tools');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control admintools','Administrative Tools');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.AutoPlay','AutoPlay');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.BackupAndRestoreCenter','Backup and Restore (Windows 7)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.BitLockerDriveEncryption','BitLocker Drive Encryption');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.ColorManagement','Color Management');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.CredentialManager','Credential Manager');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.DateAndTime','Date and Time (Date and Time)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control date/time','Date and Time (Date and Time)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.DefaultPrograms','Default Programs');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.DeviceManager','Device Manager');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.DevicesAndPrinters','Devices and Printers');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control printers','Devices and Printers');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.EaseOfAccessCenter','Ease of Access Center');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.FolderOptions','File Explorer Options (General tab)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control folders','File Explorer Options (General tab)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.FileHistory','File History');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.Fonts','Fonts');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control fonts','Fonts');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.GameControllers','Game Controllers');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.GetPrograms','Get Programs');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.HomeGroup','HomeGroup');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.IndexingOptions','Indexing Options');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.Infrared','Infrared');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.InfraredOptions','Infrared');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control international','International');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.InternetOptions','Internet Properties (General tab)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.Keyboard','Keyboard');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control keyboard','Keyboard');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.Language','Language');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.Mouse','Mouse Properties (Buttons tab 0)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control mouse','Mouse Properties (Buttons tab 0)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control netconnections','Net Connections');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.NetworkAndSharingCenter','Network and Sharing Center');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.OfflineFiles','Offline Files');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.PhoneAndModem','Phone and Modem');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.PowerOptions','Power Options');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.PowerOptions /page pageCreateNewPlan','Power Options - Create a Power Plan');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.PowerOptions /page pagePlanSettings','Power Options - Edit Plan Settings');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.PowerOptions /page pageGlobalSettings','Power Options - System Settings');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.ProgramsAndFeatures','Programs and Features');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.Recovery','Recovery');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.RegionalAndLanguageOptions /page /p:"Administrative"','Region (Administrative tab)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.RegionAndLanguage','Region (Formats tab)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.RegionalAndLanguageOptions /page /p:"Location"','Region (Location tab)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.RemoteAppAndDesktopConnections','RemoteApp and Desktop Connections');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.ScannersAndCameras','Scanners and Cameras');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.ActionCenter','Security and Maintenance');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.DefaultPrograms /page pageFileAssoc','Set Associations');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.DefaultPrograms /page pageDefaultProgram','Set Default Programs');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.Sound','Sound (Playback tab)');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.SpeechRecognition','Speech Recognition');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.StorageSpaces','Storage Spaces');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.SyncCenter','Sync Center');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.System','System');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.TabletPCSettings','Tablet PC Settings');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.TextToSpeech','Text to Speech');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.UserAccounts','User Accounts');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control userpasswords','User Passwords');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.WindowsFirewall','Windows Defender Firewall');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.MobilityCenter','Windows Mobility Center');
INSERT INTO windowsshortcuts (category, shortcut, extension) VALUES ('Control Commands cmd','control /name Microsoft.iSCSIInitiator','iSCSI Initiator');
