CREATE TABLE windowsshortcuts(
	type VARCHAR(35),
	shortcut VARCHAR(85),
	extension VARCHAR(0)
);

INSERT INTO windowsshortcuts(type,shortcut,extension)
VALUES
('type','shortcut','extension'),
('Desktop Shortcuts','Windows Key   ＋ Tab','Open Task view。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ D','Add a virtual desktop。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Right arrow','Switch between virtual desktops you’ve created on the right。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Left arrow','Switch between virtual desktops you’ve created on the left。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ F4','Close the virtual desktop you’re using。'),
('Desktop Shortcuts','Windows Key shortcuts',''),
('Desktop Shortcuts','Windows Key','Open Start menu。'),
('Desktop Shortcuts','Windows Key  ＋ A','Open Action center。'),
('Desktop Shortcuts','Windows Key  ＋ Alt ＋ D','Open date and time in the Taskbar。'),
('Desktop Shortcuts','Windows Key  ＋ Alt ＋ Number （0ー9）','Open Jump List of the app in number position in the Taskbar。'),
('Desktop Shortcuts','Windows Key  ＋ B','Set focus notification area in the Taskbar。'),
('Desktop Shortcuts','Windows Key  ＋ Comma （、）','Temporarily peek at the desktop。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ D','Create a virtual desktop。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Enter','Open Narrator。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ F','Open search for the device on a domain network。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ F4','Close active virtual desktop。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Left arrow','Switch to the virtual desktop on the left。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Number （0ー9）','Switch to the last active window of the app in the number position in the Taskbar。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Q','Open Quick Assist。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Right arrow','Switch to the virtual desktop on the right。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Shift ＋ B','Wake up the device when black or a blank screen。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Shift ＋ Number （0ー9）','Open another instance as an administrator of the app in the number position in the Taskbar。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Spacebar','Change previous selected input option。'),
('Desktop Shortcuts','Windows Key  ＋ D','Display and hide the desktop。'),
('Desktop Shortcuts','Windows Key  ＋ Down arrow key','Minimize app windows。'),
('Desktop Shortcuts','Windows Key  ＋ E','Open File Explorer。'),
('Desktop Shortcuts','Windows Key  ＋ Esc','Exit magnifier。'),
('Desktop Shortcuts','Windows Key  ＋ F','Launch Feedback Hub app。'),
('Desktop Shortcuts','Windows Key  ＋ Forwardーslash （/）','Start IME reconversion。'),
('Desktop Shortcuts','Windows Key  ＋ G','Launch Game bar app。'),
('Desktop Shortcuts','Windows Key  ＋ H','Open dictation feature。'),
('Desktop Shortcuts','Windows Key  ＋ Home','Minimize or maximize all but the active desktop window。'),
('Desktop Shortcuts','Windows Key  ＋ I','Open Settings。'),
('Desktop Shortcuts','Windows Key  ＋ J','Set focus on a tip for Windows 10 when applicable。'),
('Desktop Shortcuts','Windows Key  ＋ K','Open Connect settings。'),
('Desktop Shortcuts','Windows Key  ＋ L','Locks computer。'),
('Desktop Shortcuts','Windows Key  ＋ Left arrow key','Snap app or window left。'),
('Desktop Shortcuts','Windows Key  ＋ M','Minimize all windows。'),
('Desktop Shortcuts','Windows Key  ＋ Minus （ー）','Zoom out using the magnifier。'),
('Desktop Shortcuts','Windows Key  ＋ Number （0ー9）','Open the app in number position in the Taskbar。'),
('Desktop Shortcuts','Windows Key  ＋ O','Lock device orientation。'),
('Desktop Shortcuts','Windows Key  ＋ P','Open Project settings。'),
('Desktop Shortcuts','Windows Key  ＋ Pause','Show System Properties dialog box。'),
('Desktop Shortcuts','Windows Key  ＋ Period （。） or Semicolon （;）','Open emoji panel。'),
('Desktop Shortcuts','Windows Key  ＋ Plus （＋）','Zoom in using the magnifier。'),
('Desktop Shortcuts','Windows Key  ＋ PrtScn','Capture a full screenshot in the ”Screenshots” folder。'),
('Desktop Shortcuts','Windows Key  ＋ R','Open Run command。'),
('Desktop Shortcuts','Windows Key  ＋ Right arrow key','Snap app or window right。'),
('Desktop Shortcuts','Windows Key  ＋ S （or Q）','Open Search。'),
('Desktop Shortcuts','Windows Key  ＋ Shift ＋ Down arrow key','Windows 11： Restore the window if it is snapped or maximized。 Windows 10： Maximize or minimize active windows vertically while maintaining width。'),
('Desktop Shortcuts','Windows Key  ＋ Shift ＋ Left arrow key','Move active window to monitor on the left。'),
('Desktop Shortcuts','Windows Key  ＋ Shift ＋ M','Restore minimized windows on the desktop。'),
('Desktop Shortcuts','Windows Key  ＋ Shift ＋ Number （0ー9）','Open another app instance in the number position in the Taskbar。'),
('Desktop Shortcuts','Windows Key  ＋ Shift ＋ Right arrow key','Move active window to monitor on the right。'),
('Desktop Shortcuts','Windows Key  ＋ Shift ＋ S','Create part of the screen screenshot。'),
('Desktop Shortcuts','Windows Key  ＋ Shift ＋ Up arrow key','Stretch desktop window to the top and bottom of the screen。'),
('Desktop Shortcuts','Windows Key  ＋ Shift ＋ V','Cycle through notifications。'),
('Desktop Shortcuts','Windows Key  ＋ Spacebar','Change keyboard layout and input language。'),
('Desktop Shortcuts','Windows Key  ＋ T','Cycle through apps in the Taskbar。'),
('Desktop Shortcuts','Windows Key  ＋ Tab','Open Task View。'),
('Desktop Shortcuts','Windows Key  ＋ U','Open Ease of Access settings。'),
('Desktop Shortcuts','Windows Key  ＋ Up arrow key','Maximize app windows。'),
('Desktop Shortcuts','Windows Key  ＋ V','Open Clipboard bin。'),
('Desktop Shortcuts','Windows Key  ＋ W','Open the Windows Ink Workspace。'),
('Desktop Shortcuts','Windows Key  ＋ X','Open Quick Link menu。'),
('Desktop Shortcuts','Windows Key  ＋ Y','Change input between desktop and Mixed Reality。'),
('Desktop Shortcuts','Windows Key  ＋ Z','Switch input between the desktop experience and Windows Mixed Reality。'),
('File Explorer Shortcuts','Alt ＋ D','Select address bar。'),
('File Explorer Shortcuts','Alt ＋ Enter','Open Properties settings for the selected item。'),
('File Explorer Shortcuts','Alt ＋ Left arrow key （or Backspace）','View previous folder。'),
('File Explorer Shortcuts','Alt ＋ P','Display preview panel。'),
('File Explorer Shortcuts','Alt ＋ Right arrow key','View next folder。'),
('File Explorer Shortcuts','Alt ＋ Up arrow','Move up a level in the folder path。'),
('File Explorer Shortcuts','Ctrl ＋ E （or F）','Select search box。'),
('File Explorer Shortcuts','Ctrl ＋ F （or F3）','Start search。'),
('File Explorer Shortcuts','Ctrl ＋ L','Focus on the address bar。'),
('File Explorer Shortcuts','Ctrl ＋ Mouse scroll wheel','Change view file and folder。'),
('File Explorer Shortcuts','Ctrl ＋ N','Open new window。'),
('File Explorer Shortcuts','Ctrl ＋ Shift ＋ E','Expands all folders from the tree in the navigation pane。'),
('File Explorer Shortcuts','Ctrl ＋ Shift ＋ N','Creates a new folder on desktop or File Explorer。'),
('File Explorer Shortcuts','Ctrl ＋ Shift ＋ Number （1ー8）','Changes folder view。'),
('File Explorer Shortcuts','Ctrl ＋ W','Close active window。'),
('File Explorer Shortcuts','End','Scroll to the bottom of the window。'),
('File Explorer Shortcuts','F11','Switch active window fullーscreen mode。'),
('File Explorer Shortcuts','F2','Rename selected item。'),
('File Explorer Shortcuts','F4','Switch focus to address bar。'),
('File Explorer Shortcuts','F5','Refresh File Explorer’s current view。'),
('File Explorer Shortcuts','F6','Cycle through elements on the screen。'),
('File Explorer Shortcuts','Home','Scroll to the top of the window。'),
('File Explorer Shortcuts','Windows key  ＋ E','Open File Explorer。'),
('Windows Settings Page Shortcuts','Utilize the below shortcuts to navigate quickly on the Windows Settings page。',''),
('Windows Settings Page Shortcuts','Alt ＋ underline letter','Actions the setting identified by the letter。'),
('Windows Settings Page Shortcuts','Arrow keys','Select a button of the active setting。'),
('Windows Settings Page Shortcuts','Backspace','Opens the folder oneーlevel app in the Open or Save As dialog。'),
('Windows Settings Page Shortcuts','Ctrl ＋ number of tab','Jumps to tab position。'),
('Windows Settings Page Shortcuts','Ctrl ＋ Shift ＋ Tab','Cycles back through the tabs。'),
('Windows Settings Page Shortcuts','Ctrl ＋ Tab','Cycles forward through the tabs。'),
('Windows Settings Page Shortcuts','Shift ＋ Tab','Moves back through the settings。'),
('Windows Settings Page Shortcuts','Spacebar','Checks or clears the option in focus。'),
('Windows Settings Page Shortcuts','Tab','Moves forward through the settings。'),
('Command prompt shortcuts','Use the following keyboard shortcuts to work more efficiently。',''),
('Command prompt shortcuts','Ctrl ＋ A','Select all content of the current line。'),
('Command prompt shortcuts','Ctrl ＋ C （or Ctrl ＋ Insert）','Copy selected items to clipboard。'),
('Command prompt shortcuts','Ctrl ＋ Down arrow key','Move screen down one line。'),
('Command prompt shortcuts','Ctrl ＋ End','Scroll to the bottom of the console。'),
('Command prompt shortcuts','Ctrl ＋ F','Open search for Command Prompt。'),
('Command prompt shortcuts','Ctrl ＋ Home','Scroll to the top of the console。'),
('Command prompt shortcuts','Ctrl ＋ M','Starts mark mode。'),
('Command prompt shortcuts','Ctrl ＋ Up arrow key','Move the screen up one line。'),
('Command prompt shortcuts','Ctrl ＋ V （or Shift ＋ Insert）','Paste content from clipboard。'),
('Command prompt shortcuts','Left or right arrow keys','Move the cursor left or right in the current line。'),
('Command prompt shortcuts','Page Down','Move cursor one page down。'),
('Command prompt shortcuts','Page Up','Move cursor one page up。'),
('Command prompt shortcuts','Up or down arrow keys','Cycle through the command history of the current session。'),
('Text editing shortcuts','Use the following list of shortcuts to edit the text more quickly and efficiently。',''),
('Text editing shortcuts','Backspace','Delete characters to the left'),
('Text editing shortcuts','Ctrl ＋ =','Make selected text subscript'),
('Text editing shortcuts','Ctrl ＋ A','Select all text'),
('Text editing shortcuts','Ctrl ＋ B','Make selected text bold'),
('Text editing shortcuts','Ctrl ＋ Backspace','Delete words to the left'),
('Text editing shortcuts','Ctrl ＋ C','Copy text'),
('Text editing shortcuts','Ctrl ＋ Del','Delete words to the right'),
('Text editing shortcuts','Ctrl ＋ Down Arrow','Go to end of line break'),
('Text editing shortcuts','Ctrl ＋ End','Go to the end of the document'),
('Text editing shortcuts','Ctrl ＋ F','Find text'),
('Text editing shortcuts','Ctrl ＋ H','Find and replace text'),
('Text editing shortcuts','Ctrl ＋ Home','Go to the beginning of the document'),
('Text editing shortcuts','Ctrl ＋ I','Make selected text italic'),
('Text editing shortcuts','Ctrl ＋ Left Arrow','Go to beginning of previous word'),
('Text editing shortcuts','Ctrl ＋ Right Arrow','Go to beginning of next word'),
('Text editing shortcuts','Ctrl ＋ Shift ＋ =','Make selected text superscript'),
('Text editing shortcuts','Ctrl ＋ U','Underline selected text'),
('Text editing shortcuts','Ctrl ＋ Up Arrow','Go to beginning of line break'),
('Text editing shortcuts','Ctrl ＋ V','Paste text'),
('Text editing shortcuts','Ctrl ＋ X','Cut text'),
('Text editing shortcuts','Ctrl ＋ Y','Redo text'),
('Text editing shortcuts','Ctrl ＋ Z','Undo text'),
('Text editing shortcuts','Delete','Delete characters to the right'),
('Text editing shortcuts','Down Arrow','Go down one row'),
('Text editing shortcuts','End','Go to the end of the current line'),
('Text editing shortcuts','Home','Go to the beginning of the current line'),
('Text editing shortcuts','Left Arrow','Go to the left or to the end of previous line break'),
('Text editing shortcuts','Page Down','Move down one frame'),
('Text editing shortcuts','Page Up','Move up one frame'),
('Text editing shortcuts','Right Arrow','Go to the right or to the beginning of next line break'),
('Text editing shortcuts','Shift ＋ Ctrl ＋ Down','Select paragraphs to the right'),
('Text editing shortcuts','Shift ＋ Ctrl ＋ End','Select text between the cursor and the end of the document'),
('Text editing shortcuts','Shift ＋ Ctrl ＋ Home','Select text between the cursor and the beginning of the document'),
('Text editing shortcuts','Shift ＋ Ctrl ＋ Left','Select words to the left'),
('Text editing shortcuts','Shift ＋ Ctrl ＋ Right','Select words to the right'),
('Text editing shortcuts','Shift ＋ Ctrl ＋ Up','Select paragraphs to the left'),
('Text editing shortcuts','Shift ＋ Down Arrow','Select lines downwards'),
('Text editing shortcuts','Shift ＋ End','Select text between the cursor and the end of the current line'),
('Text editing shortcuts','Shift ＋ Home','Select text between the cursor and the beginning of the current line'),
('Text editing shortcuts','Shift ＋ Left Arrow','Select characters to the left'),
('Text editing shortcuts','Shift ＋ Page Down','Select one frame at a time of text below the cursor'),
('Text editing shortcuts','Shift ＋ Page Up','Select one frame at a time of text above the cursor'),
('Text editing shortcuts','Shift ＋ Right Arrow','Select characters to the right'),
('Text editing shortcuts','Shift ＋ Tab','Outdent'),
('Text editing shortcuts','Shift ＋ Up Arrow','Select lines upwards'),
('Text indent shortcuts','Up Arrow','Go up one row'),
('Text indent shortcuts','Taskbar Keyboard shortcuts',''),
('Text indent shortcuts','The below shortcuts allow you to navigate to the taskbar options quickly。 ',''),
('Text indent shortcuts','Ctrl ＋ Shift ＋ click a taskbar button','Open an app as an administrator。'),
('Text indent shortcuts','Ctrl ＋ click a grouped taskbar button','Cycle through the windows of the group'),
('Text indent shortcuts','Shift ＋ click a taskbar button','Open an app or quickly open another instance of an app。'),
('Text indent shortcuts','Shift ＋ rightーclick a grouped taskbar button','Show the window menu for the group。'),
('Text indent shortcuts','Shift ＋ rightーclick a taskbar button','Show the window menu for the app。'),
('Dialog Box shortcuts','The following list of shortcuts helps you perform an action within the dialog box。',''),
('Dialog Box shortcuts','Alt ＋ underlined letter','Perform the command （or select the option） that is used with that letter。'),
('Dialog Box shortcuts','Arrow keys','Select a button if the active option is a group of option buttons。'),
('Dialog Box shortcuts','Backspace','Open a folder one level up if a folder is selected in the Save As or Open dialog box。'),
('Dialog Box shortcuts','Ctrl ＋ 1、 2、 3、。。。','Move to that tab number。'),
('Dialog Box shortcuts','Ctrl ＋ Shift ＋ Tab','Move back through tabs。'),
('Dialog Box shortcuts','Ctrl ＋ Tab','Move forward through tabs。'),
('Dialog Box shortcuts','F4','Display the items in the active list。'),
('Dialog Box shortcuts','Shift ＋ Tab','Move back through options。'),
('Dialog Box shortcuts','Spacebar','Select or clear the check box if the active option is a check box。'),
('Dialog Box shortcuts','Tab','Move forward through options。'),
('Dialog Box shortcuts','Copy、 paste and other general keyboard shortcuts',''),
('Dialog Box shortcuts','Alt ＋ A','Set focus to the first icon in the Suggested actions menu。'),
('Dialog Box shortcuts','Alt ＋ Shift ＋ arrow keys','When a group or tile is in focus on the Start menu、 move it in the direction specified。'),
('Dialog Box shortcuts','Ctrl ＋ A','Select all items in a document or window。'),
('Dialog Box shortcuts','Ctrl ＋ arrow keys','Resize the Start menu when it’s open。'),
('Dialog Box shortcuts','Ctrl ＋ C （or） Ctrl ＋ Insert','Copy the selected item。'),
('Dialog Box shortcuts','Ctrl ＋ D （or） Delete','Delete the selected item and move it to the Recycle Bin。'),
('Dialog Box shortcuts','Ctrl ＋ E','Open Search （in most apps）。'),
('Dialog Box shortcuts','Ctrl ＋ Esc','Open Start。'),
('Dialog Box shortcuts','Ctrl ＋ F4','Close the active document （in apps that are fullーscreen and let you have multiple documents open at the same time）。'),
('Dialog Box shortcuts','Ctrl ＋ Shift ＋ arrow keys','When a tile is in focus on the Start menu、 move it into another tile to create a folder。'),
('Dialog Box shortcuts','Ctrl ＋ Shift ＋ V','Paste as plain text'),
('Dialog Box shortcuts','Ctrl ＋ Shift with an arrow key','Select a block of text。'),
('Dialog Box shortcuts','Ctrl ＋ Shift','Switch the keyboard layout when multiple keyboard layouts are available。'),
('Dialog Box shortcuts','Ctrl ＋ Up arrow','Move the cursor to the beginning of the previous paragraph。'),
('Dialog Box shortcuts','Ctrl ＋ V （or） Shift ＋ Insert','Paste the selected item。'),
('Dialog Box shortcuts','Ctrl ＋ X','Cut the selected item。'),
('Dialog Box shortcuts','Ctrl ＋ Y','Redo an action。'),
('Dialog Box shortcuts','Ctrl ＋ Z','Undo an action。'),
('Dialog Box shortcuts','Esc','Stop or leave the current task。'),
('Dialog Box shortcuts','F2','Rename the selected item。'),
('Dialog Box shortcuts','F3','Search for a file or folder in File Explorer。'),
('Dialog Box shortcuts','F4','Display the address bar list in File Explorer。'),
('Dialog Box shortcuts','F5','Refresh the active window。'),
('Dialog Box shortcuts','F6','Cycle through screen elements in a window or on the desktop。'),
('Dialog Box shortcuts','F10','Activate the Menu bar in the active app。'),
('Dialog Box shortcuts','Left arrow','Open the next menu to the left、 or close a submenu。'),
('Dialog Box shortcuts','Right arrow','Open the next menu to the right、 or open a submenu。'),
('Dialog Box shortcuts','Shift ＋ Delete','Delete the selected item without moving it to the Recycle Bin first。'),
('Dialog Box shortcuts','Shift with any arrow key','Select more than one item in a window or on the desktop、 or select text in a document。'),
('Dialog Box shortcuts','PrtScn','Take a screenshot of your whole screen and copy it to the clipboard。'),
('Run Commands','access。cpl','Accessibility Controls'),
('Run Commands','hdwwiz。cpl','Add Hardware Wizard'),
('Run Commands','appwiz。cpl','Add/Remove Programs'),
('Run Commands','control admintools','Administrative Tools'),
('Run Commands','wuaucpl。cpl','Automatic Updates'),
('Run Commands','fsquirt','Bluetooth Transfer Wizard'),
('Run Commands','calc','Calculator'),
('Run Commands','certmgr。msc','Certificate Manager'),
('Run Commands','charmap','Character Map'),
('Run Commands','chkdsk','Check Disk Utility'),
('Run Commands','clipbrd','Clipboard Viewer'),
('Run Commands','cmd','Command Prompt'),
('Run Commands','dcomcnfg','Component Services'),
('Run Commands','compmgmt。msc','Computer Management'),
('Run Commands','timedate。cpl','Date/Time Properties'),
('Run Commands','ddeshare','DDE Share'),
('Run Commands','devmgmt。msc','Device Manager'),
('Run Commands','directx。cpl','Direct X Control Panel （If Installed）*'),
('Run Commands','dxdiag','Direct X Troubleshooter'),
('Run Commands','cleanmgr','Disk Cleanup Utility'),
('Run Commands','dfrg。msc','Disk Defragment'),
('Run Commands','diskmgmt。msc','Disk Management'),
('Run Commands','diskpart','Disk Partition Manager'),
('Run Commands','control desktop','Display Properties'),
('Run Commands','desk。cpl','Display Properties'),
('Run Commands','control color','Display Properties （w/Appearance Tab Preselected）'),
('Run Commands','drwtsn32','Dr。 Watson System Troubleshooting Utility'),
('Run Commands','verifier','Driver Verifier Utility'),
('Run Commands','eventvwr。msc','Event Viewer'),
('Run Commands','sigverif','File Signature Verification Tool'),
('Run Commands','findfast。cpl','Findfast'),
('Run Commands','control folders','Folders Properties'),
('Run Commands','control fonts','Fonts'),
('Run Commands','fonts','Fonts Folder'),
('Run Commands','freecell','Free Cell Card Game'),
('Run Commands','joy。cpl','Game Controllers'),
('Run Commands','gpedit。msc','Group Policy Editor （XP Prof）'),
('Run Commands','mshearts','Hearts Card Game'),
('Run Commands','iexpress','Iexpress Wizard'),
('Run Commands','ciadv。msc','Indexing Service'),
('Run Commands','inetcpl。cpl','Internet Properties'),
('Run Commands','ipconfig /all','IP Configuration （Display Connection Configuration）'),
('Run Commands','ipconfig /displaydns','IP Configuration （Display DNS Cache Contents）'),
('Run Commands','ipconfig /flushdns','IP Configuration （Delete DNS Cache Contents）'),
('Run Commands','ipconfig /release','IP Configuration （Release All Connections）'),
('Run Commands','ipconfig /renew','IP Configuration （Renew All Connections）'),
('Run Commands','ipconfig /registerdns','IP Configuration （Refreshes DHCP & ReーRegisters DNS）'),
('Run Commands','ipconfig /showclassid','IP Configuration （Display DHCP Class ID）'),
('Run Commands','ipconfig /setclassid','IP Configuration （Modifies DHCP Class ID）'),
('Run Commands','jpicpl32。cpl','Java Control Panel （If Installed）'),
('Run Commands','javaws','Java Control Panel （If Installed）'),
('Run Commands','control keyboard','Keyboard Properties'),
('Run Commands','secpol。msc','Local Security Settings'),
('Run Commands','lusrmgr。msc','Local Users and Groups'),
('Run Commands','logoff','Logs You Out Of Windows'),
('Run Commands','winchat','Microsoft Chat'),
('Run Commands','winmine','Minesweeper Game'),
('Run Commands','control mouse','Mouse Properties'),
('Run Commands','main。cpl','Mouse Properties'),
('Run Commands','control netconnections','Network Connections'),
('Run Commands','ncpa。cpl','Network Connections'),
('Run Commands','netsetup。cpl','Network Setup Wizard'),
('Run Commands','notepad','Notepad'),
('Run Commands','nvtuicpl。cpl','Nview Desktop Manager （If Installed）'),
('Run Commands','packager','Object Packager'),
('Run Commands','odbccp32。cpl','ODBC Data Source Administrator'),
('Run Commands','osk','On Screen Keyboard'),
('Run Commands','ac3filter。cpl','Opens AC3 Filter （If Installed）'),
('Run Commands','password。cpl','Password Properties'),
('Run Commands','perfmon','Performance Monitor'),
('Run Commands','telephon。cpl','Phone and Modem Options'),
('Run Commands','powercfg。cpl','Power Configuration'),
('Run Commands','control printers','Printers and Faxes'),
('Run Commands','printers','Printers Folder'),
('Run Commands','eudcedit','Private Character Editor'),
('Run Commands','QuickTime。cpl','Quicktime （If Installed）'),
('Run Commands','intl。cpl','Regional Settings'),
('Run Commands','regedit','Registry Editor'),
('Run Commands','regedit32','Registry Editor'),
('Run Commands','mstsc','Remote Desktop'),
('Run Commands','ntmsmgr。msc','Removable Storage'),
('Run Commands','ntmsoprq。msc','Removable Storage Operator Requests'),
('Run Commands','rsop。msc','Resultant Set of Policy （XP Prof）'),
('Run Commands','sticpl。cpl','Scanners and Cameras'),
('Run Commands','control schedtasks','Scheduled Tasks'),
('Run Commands','wscui。cpl','Security Center'),
('Run Commands','services。msc','Services'),
('Run Commands','fsmgmt。msc','Shared Folders'),
('Run Commands','shutdown','Shuts Down Windows'),
('Run Commands','mmsys。cpl','Sounds and Audio'),
('Run Commands','spider','Spider Solitare Card Game'),
('Run Commands','cliconfg','SQL Client Configuration'),
('Run Commands','sysedit','System Configuration Editor'),
('Run Commands','msconfig','System Configuration Utility'),
('Run Commands','sfc /scannow','System File Checker Utility （Scan Immediately）'),
('Run Commands','sfc /scanonce','System File Checker Utility （Scan Once At Next Boot）'),
('Run Commands','sfc /scanboot','System File Checker Utility （Scan On Every Boot）'),
('Run Commands','sfc /revert','System File Checker Utility （Return to Default Setting） sfc /revert'),
('Run Commands','sfc /purgecache','System File Checker Utility （Purge File Cache）'),
('Run Commands',' sfc /cachesize','System File Checker Utility （Set Cache Size to size x） sfc /cachesize=x'),
('Run Commands','sysdm。cpl','System Properties'),
('Run Commands','taskmgr','Task Manager'),
('Run Commands','telnet','Telnet Client'),
('Run Commands','nusrmgr。cpl','User Account Management'),
('Run Commands','utilman','Utility Manager'),
('Run Commands','firewall。cpl','Windows Firewall'),
('Run Commands','magnify','Windows Magnifier'),
('Run Commands','wmimgmt。msc','Windows Management Infrastructure'),
('Run Commands','syskey','Windows System Security Tool'),
('Run Commands','wupdmgr','Windows Update Launches'),
('Run Commands','tourstart','Windows XP Tour Wizard'),
('Run Commands','write','Wordpad');
