DROP TABLE IF EXISTS windowsshortcuts;

CREATE TABLE windowsshortcuts(
category VARCHAR(30),
shortcut VARCHAR(35),
extension VARCHAR(85)
);

INSERT INTO windowsshortcuts(category,shortcut,extension)
VALUES
('category','shortcut','extension'),
('Command prompt shortcuts','Select all content of the current line。','Ctrl ＋ A'),
('Command prompt shortcuts','Copy selected items to clipboard。','Ctrl ＋ C （or Ctrl ＋ Insert）'),
('Command prompt shortcuts','Move screen down one line。','Ctrl ＋ Down arrow key'),
('Command prompt shortcuts','Scroll to the bottom of the console。','Ctrl ＋ End'),
('Command prompt shortcuts','Open search for Command Prompt。','Ctrl ＋ F'),
('Command prompt shortcuts','Scroll to the top of the console。','Ctrl ＋ Home'),
('Command prompt shortcuts','Starts mark mode。','Ctrl ＋ M'),
('Command prompt shortcuts','Move the screen up one line。','Ctrl ＋ Up arrow key'),
('Command prompt shortcuts','Paste content from clipboard。','Ctrl ＋ V （or Shift ＋ Insert）'),
('Command prompt shortcuts','Move the cursor left or right in the current line。','Left or right arrow keys'),
('Command prompt shortcuts','Move cursor one page down。','Page Down'),
('Command prompt shortcuts','Move cursor one page up。','Page Up'),
('Command prompt shortcuts','Cycle through the command history of the current session。','Up or down arrow keys'),
('Command prompt shortcuts','CATEGORY','Use the following keyboard shortcuts to work more efficiently。'),
('Control Commands pwsh','control /name Microsoft。AdministrativeTools','Administrative Tools'),
('Control Commands pwsh','control /name Microsoft。AutoPlay','AutoPlay'),
('Control Commands pwsh','control /name Microsoft。BackupAndRestoreCenter','Backup and Restore （Windows 7）'),
('Control Commands pwsh','control /name Microsoft。BitLockerDriveEncryption','BitLocker Drive Encryption'),
('Control Commands pwsh','control /name Microsoft。ColorManagement','Color Management'),
('Control Commands pwsh','control /name Microsoft。CredentialManager','Credential Manager'),
('Control Commands pwsh','control /name Microsoft。DateAndTime','Date and Time （Date and Time）'),
('Control Commands pwsh','control date/time','Date and Time （Date and Time）'),
('Control Commands pwsh','control /name Microsoft。DefaultPrograms','Default Programs'),
('Control Commands pwsh','control /name Microsoft。DeviceManager','Device Manager'),
('Control Commands pwsh','control /name Microsoft。DevicesAndPrinters','Devices and Printers'),
('Control Commands pwsh','control /name Microsoft。EaseOfAccessCenter','Ease of Access Center'),
('Control Commands pwsh','control /name Microsoft。FolderOptions','File Explorer Options （General tab）'),
('Control Commands pwsh','control /name Microsoft。FileHistory','File History'),
('Control Commands pwsh','control /name Microsoft。Fonts','Fonts'),
('Control Commands pwsh','control /name Microsoft。GameControllers','Game Controllers'),
('Control Commands pwsh','control /name Microsoft。GetPrograms','Get Programs'),
('Control Commands pwsh','control /name Microsoft。HomeGroup','HomeGroup'),
('Control Commands pwsh','control /name Microsoft。IndexingOptions','Indexing Options'),
('Control Commands pwsh','control /name Microsoft。Infrared','Infrared'),
('Control Commands pwsh','control /name Microsoft。InfraredOptions','Infrared'),
('Control Commands pwsh','control /name Microsoft。InternetOptions','Internet Properties （General tab）'),
('Control Commands pwsh','control /name Microsoft。Keyboard','Keyboard'),
('Control Commands pwsh','control /name Microsoft。Language','Language'),
('Control Commands pwsh','control /name Microsoft。Mouse','Mouse Properties （Buttons tab 0）'),
('Control Commands pwsh','control /name Microsoft。NetworkAndSharingCenter','Network and Sharing Center'),
('Control Commands pwsh','control /name Microsoft。OfflineFiles','Offline Files'),
('Control Commands pwsh','control /name Microsoft。PhoneAndModem','Phone and Modem'),
('Control Commands pwsh','control /name Microsoft。PowerOptions','Power Options'),
('Control Commands pwsh','control /name Microsoft。PowerOptions /page pageCreateNewPlan','Power Options ー Create a Power Plan'),
('Control Commands pwsh','control /name Microsoft。PowerOptions /page pagePlanSettings','Power Options ー Edit Plan Settings'),
('Control Commands pwsh','control /name Microsoft。PowerOptions /page pageGlobalSettings','Power Options ー System Settings'),
('Control Commands pwsh','control /name Microsoft。ProgramsAndFeatures','Programs and Features'),
('Control Commands pwsh','control /name Microsoft。Recovery','Recovery'),
('Control Commands pwsh','control /name Microsoft。RegionalAndLanguageOptions /page /p：””Administrative””','Region （Administrative tab）'),
('Control Commands pwsh','control /name Microsoft。RegionAndLanguage','Region （Formats tab）'),
('Control Commands pwsh','control /name Microsoft。RegionalAndLanguageOptions /page /p：””Location””','Region （Location tab）'),
('Control Commands pwsh','control /name Microsoft。RemoteAppAndDesktopConnections','RemoteApp and Desktop Connections'),
('Control Commands pwsh','control /name Microsoft。ScannersAndCameras','Scanners and Cameras'),
('Control Commands pwsh','control /name Microsoft。ActionCenter','Security and Maintenance'),
('Control Commands pwsh','control /name Microsoft。DefaultPrograms /page pageFileAssoc','Set Associations'),
('Control Commands pwsh','control /name Microsoft。DefaultPrograms /page pageDefaultProgram','Set Default Programs'),
('Control Commands pwsh','control /name Microsoft。Sound','Sound （Playback tab）'),
('Control Commands pwsh','control /name Microsoft。SpeechRecognition','Speech Recognition'),
('Control Commands pwsh','control /name Microsoft。StorageSpaces','Storage Spaces'),
('Control Commands pwsh','control /name Microsoft。SyncCenter','Sync Center'),
('Control Commands pwsh','control /name Microsoft。System','System'),
('Control Commands pwsh','control /name Microsoft。TabletPCSettings','Tablet PC Settings'),
('Control Commands pwsh','control /name Microsoft。TextToSpeech','Text to Speech'),
('Control Commands pwsh','control /name Microsoft。UserAccounts','User Accounts'),
('Control Commands pwsh','control /name Microsoft。WindowsFirewall','Windows Defender Firewall'),
('Control Commands pwsh','control /name Microsoft。MobilityCenter','Windows Mobility Center'),
('Control Commands pwsh','control /name Microsoft。iSCSIInitiator','iSCSI Initiator'),
('Control Commands cmd','control /name Microsoft。AdministrativeTools','Administrative Tools'),
('Control Commands cmd','control admintools','Administrative Tools'),
('Control Commands cmd','control /name Microsoft。AutoPlay','AutoPlay'),
('Control Commands cmd','control /name Microsoft。BackupAndRestoreCenter','Backup and Restore （Windows 7）'),
('Control Commands cmd','control /name Microsoft。BitLockerDriveEncryption','BitLocker Drive Encryption'),
('Control Commands cmd','control /name Microsoft。ColorManagement','Color Management'),
('Control Commands cmd','control /name Microsoft。CredentialManager','Credential Manager'),
('Control Commands cmd','control /name Microsoft。DateAndTime','Date and Time （Date and Time）'),
('Control Commands cmd','control date/time','Date and Time （Date and Time）'),
('Control Commands cmd','control /name Microsoft。DefaultPrograms','Default Programs'),
('Control Commands cmd','control /name Microsoft。DeviceManager','Device Manager'),
('Control Commands cmd','control /name Microsoft。DevicesAndPrinters','Devices and Printers'),
('Control Commands cmd','control printers','Devices and Printers'),
('Control Commands cmd','control /name Microsoft。EaseOfAccessCenter','Ease of Access Center'),
('Control Commands cmd','control /name Microsoft。FolderOptions','File Explorer Options （General tab）'),
('Control Commands cmd','control folders','File Explorer Options （General tab）'),
('Control Commands cmd','control /name Microsoft。FileHistory','File History'),
('Control Commands cmd','control /name Microsoft。Fonts','Fonts'),
('Control Commands cmd','control fonts','Fonts'),
('Control Commands cmd','control /name Microsoft。GameControllers','Game Controllers'),
('Control Commands cmd','control /name Microsoft。GetPrograms','Get Programs'),
('Control Commands cmd','control /name Microsoft。HomeGroup','HomeGroup'),
('Control Commands cmd','control /name Microsoft。IndexingOptions','Indexing Options'),
('Control Commands cmd','control /name Microsoft。Infrared','Infrared'),
('Control Commands cmd','control /name Microsoft。InfraredOptions','Infrared'),
('Control Commands cmd','control international','International'),
('Control Commands cmd','control /name Microsoft。InternetOptions','Internet Properties （General tab）'),
('Control Commands cmd','control /name Microsoft。Keyboard','Keyboard'),
('Control Commands cmd','control keyboard','Keyboard'),
('Control Commands cmd','control /name Microsoft。Language','Language'),
('Control Commands cmd','control /name Microsoft。Mouse','Mouse Properties （Buttons tab 0）'),
('Control Commands cmd','control mouse','Mouse Properties （Buttons tab 0）'),
('Control Commands cmd','control netconnections','Net Connections'),
('Control Commands cmd','control /name Microsoft。NetworkAndSharingCenter','Network and Sharing Center'),
('Control Commands cmd','control /name Microsoft。OfflineFiles','Offline Files'),
('Control Commands cmd','control /name Microsoft。PhoneAndModem','Phone and Modem'),
('Control Commands cmd','control /name Microsoft。PowerOptions','Power Options'),
('Control Commands cmd','control /name Microsoft。PowerOptions /page pageCreateNewPlan','Power Options ー Create a Power Plan'),
('Control Commands cmd','control /name Microsoft。PowerOptions /page pagePlanSettings','Power Options ー Edit Plan Settings'),
('Control Commands cmd','control /name Microsoft。PowerOptions /page pageGlobalSettings','Power Options ー System Settings'),
('Control Commands cmd','control /name Microsoft。ProgramsAndFeatures','Programs and Features'),
('Control Commands cmd','control /name Microsoft。Recovery','Recovery'),
('Control Commands cmd','control /name Microsoft。RegionalAndLanguageOptions /page /p：””Administrative””','Region （Administrative tab）'),
('Control Commands cmd','control /name Microsoft。RegionAndLanguage','Region （Formats tab）'),
('Control Commands cmd','control /name Microsoft。RegionalAndLanguageOptions /page /p：””Location””','Region （Location tab）'),
('Control Commands cmd','control /name Microsoft。RemoteAppAndDesktopConnections','RemoteApp and Desktop Connections'),
('Control Commands cmd','control /name Microsoft。ScannersAndCameras','Scanners and Cameras'),
('Control Commands cmd','control /name Microsoft。ActionCenter','Security and Maintenance'),
('Control Commands cmd','control /name Microsoft。DefaultPrograms /page pageFileAssoc','Set Associations'),
('Control Commands cmd','control /name Microsoft。DefaultPrograms /page pageDefaultProgram','Set Default Programs'),
('Control Commands cmd','control /name Microsoft。Sound','Sound （Playback tab）'),
('Control Commands cmd','control /name Microsoft。SpeechRecognition','Speech Recognition'),
('Control Commands cmd','control /name Microsoft。StorageSpaces','Storage Spaces'),
('Control Commands cmd','control /name Microsoft。SyncCenter','Sync Center'),
('Control Commands cmd','control /name Microsoft。System','System'),
('Control Commands cmd','control /name Microsoft。TabletPCSettings','Tablet PC Settings'),
('Control Commands cmd','control /name Microsoft。TextToSpeech','Text to Speech'),
('Control Commands cmd','control /name Microsoft。UserAccounts','User Accounts'),
('Control Commands cmd','control userpasswords','User Passwords'),
('Control Commands cmd','control /name Microsoft。WindowsFirewall','Windows Defender Firewall'),
('Control Commands cmd','control /name Microsoft。MobilityCenter','Windows Mobility Center'),
('Control Commands cmd','control /name Microsoft。iSCSIInitiator','iSCSI Initiator'),
('Control Panel Applets（CPL）','appwiz。cpl','Opens Programs and Features、 allowing you to uninstall or change installed applications。'),
('Control Panel Applets（CPL）','bthprops。cpl','Opens Bluetooth settings、 allowing you to manage Bluetooth devices and configurations。'),
('Control Panel Applets（CPL）','desk。cpl','Opens Display settings、 where you can configure screen resolution、 orientation、 and multiple display options。'),
('Control Panel Applets（CPL）','firewall。cpl','Opens Windows Firewall settings、 where you can configure firewall rules and exceptions。'),
('Control Panel Applets（CPL）','hdwwiz。cpl','Opens the Add Hardware Wizard、 which guides you through the process of installing new hardware。'),
('Control Panel Applets（CPL）','inetcpl。cpl','Opens Internet Properties、 where you can manage settings related to Internet Explorer and your internet connection。'),
('Control Panel Applets（CPL）','intl。cpl','Opens Region and Language settings、 allowing you to configure language、 locale、 and formats。'),
('Control Panel Applets（CPL）','irprops。cpl','Opens Infrared （IR） properties、 allowing you to manage infrared device settings。'),
('Control Panel Applets（CPL）','joy。cpl','Opens Game Controllers settings、 where you can manage and test connected game controllers。'),
('Control Panel Applets（CPL）','main。cpl','Opens Mouse properties for configuring mouse settings。'),
('Control Panel Applets（CPL）','mmsys。cpl','Opens Sound settings、 where you can manage audio devices and configurations。'),
('Control Panel Applets（CPL）','ncpa。cpl','Opens Network Connections、 allowing you to manage network adapters and connections。'),
('Control Panel Applets（CPL）','powercfg。cpl','Opens Power Options、 where you can configure power plans and settings。'),
('Control Panel Applets（CPL）','sysdm。cpl','Opens System Properties、 where you can manage system settings、 including hardware profiles and system protection。'),
('Control Panel Applets（CPL）','telephon。cpl','Opens Phone and Modem settings、 allowing you to manage telephony devices。'),
('Control Panel Applets（CPL）','timedate。cpl','Opens Date and Time settings、 where you can configure the system clock and time zone。'),
('Control Panel Applets（CPL）','wscui。cpl','Opens Windows Security Center、 where you can manage security settings for your system。'),
('Desktop Shortcuts','Windows Key','Open Start menu。'),
('Desktop Shortcuts','Windows Key   ＋ Tab','Open Task view。'),
('Desktop Shortcuts','Windows Key  ＋ A','Open Action center。'),
('Desktop Shortcuts','Windows Key  ＋ Alt ＋ D','Open date and time in the Taskbar。'),
('Desktop Shortcuts','Windows Key  ＋ Alt ＋ Number （0ー9）','Open Jump List of the app in number position in the Taskbar。'),
('Desktop Shortcuts','Windows Key  ＋ B','Set focus notification area in the Taskbar。'),
('Desktop Shortcuts','Windows Key  ＋ Comma （、）','Temporarily peek at the desktop。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ D','Add a virtual desktop。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ D','Create a virtual desktop。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Enter','Open Narrator。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ F','Open search for the device on a domain network。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ F4','Close active virtual desktop。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ F4','Close the virtual desktop you’re using。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Left arrow','Switch between virtual desktops you’ve created on the left。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Left arrow','Switch to the virtual desktop on the left。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Number （0ー9）','Switch to the last active window of the app in the number position in the Taskbar。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Q','Open Quick Assist。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Right arrow','Switch between virtual desktops you’ve created on the right。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Right arrow','Switch to the virtual desktop on the right。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Shift ＋ B','Wake up the device when black or a blank screen。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Shift ＋ Number （0ー9）','Open another instance as an administrator of the app in the number position in the Taskbar。'),
('Desktop Shortcuts','Windows Key  ＋ Ctrl ＋ Spacebar','Change previous selected input option。'),
('Desktop Shortcuts','Windows Key  ＋ D','Display and hide the desktop。'),
('Desktop Shortcuts','Windows Key  ＋ Down arrow key','Minimize app windows。'),
('Desktop Shortcuts','Windows Key  ＋ E','Open File Explorer。'),
('Desktop Shortcuts','Windows Key  ＋ Esc','Exit magnifier。'),
('Desktop Shortcuts','Windows Key  ＋ F','Launch Feedback Hub app。'),
('Desktop Shortcuts','Windows Key  ＋ Forwardーslash （/）','Start IME reconversion。'),
('Desktop Shortcuts','Windows Key  ＋ G','Launch Game bar app。'),
('Desktop Shortcuts','Windows Key  ＋ H','Open dictation feature。'),
('Desktop Shortcuts','Windows Key  ＋ Home','Minimize or maximize all but the active desktop window。'),
('Desktop Shortcuts','Windows Key  ＋ I','Open Settings。'),
('Desktop Shortcuts','Windows Key  ＋ J','Set focus on a tip for Windows 10 when applicable。'),
('Desktop Shortcuts','Windows Key  ＋ K','Open Connect settings。'),
('Desktop Shortcuts','Windows Key  ＋ L','Locks computer。'),
('Desktop Shortcuts','Windows Key  ＋ Left arrow key','Snap app or window left。'),
('Desktop Shortcuts','Windows Key  ＋ M','Minimize all windows。'),
('Desktop Shortcuts','Windows Key  ＋ Minus （ー）','Zoom out using the magnifier。'),
('Desktop Shortcuts','Windows Key  ＋ Number （0ー9）','Open the app in number position in the Taskbar。'),
('Desktop Shortcuts','Windows Key  ＋ O','Lock device orientation。'),
('Desktop Shortcuts','Windows Key  ＋ P','Open Project settings。'),
('Desktop Shortcuts','Windows Key  ＋ Pause','Show System Properties dialog box。'),
('Desktop Shortcuts','Windows Key  ＋ Period （。） or Semicolon （;）','Open emoji panel。'),
('Desktop Shortcuts','Windows Key  ＋ Plus （＋）','Zoom in using the magnifier。'),
('Desktop Shortcuts','Windows Key  ＋ PrtScn','Capture a full screenshot in the ”Screenshots” folder。'),
('Desktop Shortcuts','Windows Key  ＋ R','Open Run command。'),
('Desktop Shortcuts','Windows Key  ＋ Right arrow key','Snap app or window right。'),
('Desktop Shortcuts','Windows Key  ＋ S （or Q）','Open Search。'),
('Desktop Shortcuts','Windows Key  ＋ Shift ＋ Down arrow key','Windows 11： Restore the window if it is snapped or maximized。 Windows 10： Maximize or minimize active windows vertically while maintaining width。'),
('Desktop Shortcuts','Windows Key  ＋ Shift ＋ Left arrow key','Move active window to monitor on the left。'),
('Desktop Shortcuts','Windows Key  ＋ Shift ＋ M','Restore minimized windows on the desktop。'),
('Desktop Shortcuts','Windows Key  ＋ Shift ＋ Number （0ー9）','Open another app instance in the number position in the Taskbar。'),
('Desktop Shortcuts','Windows Key  ＋ Shift ＋ Right arrow key','Move active window to monitor on the right。'),
('Desktop Shortcuts','Windows Key  ＋ Shift ＋ S','Create part of the screen screenshot。'),
('Desktop Shortcuts','Windows Key  ＋ Shift ＋ Up arrow key','Stretch desktop window to the top and bottom of the screen。'),
('Desktop Shortcuts','Windows Key  ＋ Shift ＋ V','Cycle through notifications。'),
('Desktop Shortcuts','Windows Key  ＋ Spacebar','Change keyboard layout and input language。'),
('Desktop Shortcuts','Windows Key  ＋ T','Cycle through apps in the Taskbar。'),
('Desktop Shortcuts','Windows Key  ＋ Tab','Open Task View。'),
('Desktop Shortcuts','Windows Key  ＋ U','Open Ease of Access settings。'),
('Desktop Shortcuts','Windows Key  ＋ Up arrow key','Maximize app windows。'),
('Desktop Shortcuts','Windows Key  ＋ V','Open Clipboard bin。'),
('Desktop Shortcuts','Windows Key  ＋ W','Open the Windows Ink Workspace。'),
('Desktop Shortcuts','Windows Key  ＋ X','Open Quick Link menu。'),
('Desktop Shortcuts','Windows Key  ＋ Y','Change input between desktop and Mixed Reality。'),
('Desktop Shortcuts','Windows Key  ＋ Z','Switch input between the desktop experience and Windows Mixed Reality。'),
('Desktop Shortcuts','Windows Key shortcuts','CATEGORY'),
('Dialog Box shortcuts','Alt ＋ A','Set focus to the first icon in the Suggested actions menu。'),
('Dialog Box shortcuts','Alt ＋ Shift ＋ arrow keys','When a group or tile is in focus on the Start menu、 move it in the direction specified。'),
('Dialog Box shortcuts','Alt ＋ underlined letter','Perform the command （or select the option） that is used with that letter。'),
('Dialog Box shortcuts','Arrow keys','Select a button if the active option is a group of option buttons。'),
('Dialog Box shortcuts','Backspace','Open a folder one level up if a folder is selected in the Save As or Open dialog box。'),
('Dialog Box shortcuts','Copy、 paste and other general keyboard shortcuts','CATEGORY'),
('Dialog Box shortcuts','Ctrl ＋ 1、 2、 3、。。。','Move to that tab number。'),
('Dialog Box shortcuts','Ctrl ＋ A','Select all items in a document or window。'),
('Dialog Box shortcuts','Ctrl ＋ C （or） Ctrl ＋ Insert','Copy the selected item。'),
('Dialog Box shortcuts','Ctrl ＋ D （or） Delete','Delete the selected item and move it to the Recycle Bin。'),
('Dialog Box shortcuts','Ctrl ＋ E','Open Search （in most apps）。'),
('Dialog Box shortcuts','Ctrl ＋ Esc','Open Start。'),
('Dialog Box shortcuts','Ctrl ＋ F4','Close the active document （in apps that are fullーscreen and let you have multiple documents open at the same time）。'),
('Dialog Box shortcuts','Ctrl ＋ Shift','Switch the keyboard layout when multiple keyboard layouts are available。'),
('Dialog Box shortcuts','Ctrl ＋ Shift with an arrow key','Select a block of text。'),
('Dialog Box shortcuts','Ctrl ＋ Shift ＋ Tab','Move back through tabs。'),
('Dialog Box shortcuts','Ctrl ＋ Shift ＋ V','Paste as plain text'),
('Dialog Box shortcuts','Ctrl ＋ Shift ＋ arrow keys','When a tile is in focus on the Start menu、 move it into another tile to create a folder。'),
('Dialog Box shortcuts','Ctrl ＋ Tab','Move forward through tabs。'),
('Dialog Box shortcuts','Ctrl ＋ Up arrow','Move the cursor to the beginning of the previous paragraph。'),
('Dialog Box shortcuts','Ctrl ＋ V （or） Shift ＋ Insert','Paste the selected item。'),
('Dialog Box shortcuts','Ctrl ＋ X','Cut the selected item。'),
('Dialog Box shortcuts','Ctrl ＋ Y','Redo an action。'),
('Dialog Box shortcuts','Ctrl ＋ Z','Undo an action。'),
('Dialog Box shortcuts','Ctrl ＋ arrow keys','Resize the Start menu when it’s open。'),
('Dialog Box shortcuts','Esc','Stop or leave the current task。'),
('Dialog Box shortcuts','F10','Activate the Menu bar in the active app。'),
('Dialog Box shortcuts','F2','Rename the selected item。'),
('Dialog Box shortcuts','F3','Search for a file or folder in File Explorer。'),
('Dialog Box shortcuts','F4','Display the address bar list in File Explorer。'),
('Dialog Box shortcuts','F4','Display the items in the active list。'),
('Dialog Box shortcuts','F5','Refresh the active window。'),
('Dialog Box shortcuts','F6','Cycle through screen elements in a window or on the desktop。'),
('Dialog Box shortcuts','Left arrow','Open the next menu to the left、 or close a submenu。'),
('Dialog Box shortcuts','PrtScn','Take a screenshot of your whole screen and copy it to the clipboard。'),
('Dialog Box shortcuts','Right arrow','Open the next menu to the right、 or open a submenu。'),
('Dialog Box shortcuts','Shift with any arrow key','Select more than one item in a window or on the desktop、 or select text in a document。'),
('Dialog Box shortcuts','Shift ＋ Delete','Delete the selected item without moving it to the Recycle Bin first。'),
('Dialog Box shortcuts','Shift ＋ Tab','Move back through options。'),
('Dialog Box shortcuts','Spacebar','Select or clear the check box if the active option is a check box。'),
('Dialog Box shortcuts','Tab','Move forward through options。'),
('Dialog Box shortcuts','The following list of shortcuts helps you perform an action within the dialog box。','CATEGORY'),
('File Explorer Shortcuts','Alt ＋ D','Select address bar。'),
('File Explorer Shortcuts','Alt ＋ Enter','Open Properties settings for the selected item。'),
('File Explorer Shortcuts','Alt ＋ Left arrow key （or Backspace）','View previous folder。'),
('File Explorer Shortcuts','Alt ＋ P','Display preview panel。'),
('File Explorer Shortcuts','Alt ＋ Right arrow key','View next folder。'),
('File Explorer Shortcuts','Alt ＋ Up arrow','Move up a level in the folder path。'),
('File Explorer Shortcuts','Ctrl ＋ E （or F）','Select search box。'),
('File Explorer Shortcuts','Ctrl ＋ F （or F3）','Start search。'),
('File Explorer Shortcuts','Ctrl ＋ L','Focus on the address bar。'),
('File Explorer Shortcuts','Ctrl ＋ Mouse scroll wheel','Change view file and folder。'),
('File Explorer Shortcuts','Ctrl ＋ N','Open new window。'),
('File Explorer Shortcuts','Ctrl ＋ Shift ＋ E','Expands all folders from the tree in the navigation pane。'),
('File Explorer Shortcuts','Ctrl ＋ Shift ＋ N','Creates a new folder on desktop or File Explorer。'),
('File Explorer Shortcuts','Ctrl ＋ Shift ＋ Number （1ー8）','Changes folder view。'),
('File Explorer Shortcuts','Ctrl ＋ W','Close active window。'),
('File Explorer Shortcuts','End','Scroll to the bottom of the window。'),
('File Explorer Shortcuts','F11','Switch active window fullーscreen mode。'),
('File Explorer Shortcuts','F2','Rename selected item。'),
('File Explorer Shortcuts','F4','Switch focus to address bar。'),
('File Explorer Shortcuts','F5','Refresh File Explorer’s current view。'),
('File Explorer Shortcuts','F6','Cycle through elements on the screen。'),
('File Explorer Shortcuts','Home','Scroll to the top of the window。'),
('File Explorer Shortcuts','Windows key  ＋ E','Open File Explorer。'),
('Microsoft Management Consoles（MSCs）','WF。msc','Opens Windows Firewall with Advanced Security、 where you can configure inbound and outbound firewall rules。'),
('Microsoft Management Consoles（MSCs）','azman。msc','Used for managing authorization policies。 It allows you to create and manage roleーbased access control。'),
('Microsoft Management Consoles（MSCs）','certlm。msc','Displays the local machine’s certificate store。 You can manage certificates for the computer。'),
('Microsoft Management Consoles（MSCs）','certmgr。msc','Displays the user certificate store。 It allows you to manage certificates for the current user。'),
('Microsoft Management Consoles（MSCs）','comexp。msc','Opens the Component Services management console、 which is used to manage COM＋ applications and DCOM configuration。'),
('Microsoft Management Consoles（MSCs）','compmgmt。msc','Opens the Computer Management console、 which provides access to several system management tools、 including Disk Management、 Event Viewer、 and Services。'),
('Microsoft Management Consoles（MSCs）','devmgmt。msc','Opens Device Manager、 which allows you to view and manage hardware devices and their drivers。'),
('Microsoft Management Consoles（MSCs）','diskmgmt。msc','Opens Disk Management、 where you can manage disk partitions、 format drives、 and assign drive letters。'),
('Microsoft Management Consoles（MSCs）','eventvwr。msc','Opens Event Viewer、 which allows you to view logs related to system、 security、 and application events。'),
('Microsoft Management Consoles（MSCs）','fsmgmt。msc','Opens Shared Folders、 where you can manage shared resources on the system、 including files and sessions。'),
('Microsoft Management Consoles（MSCs）','lusrmgr。msc','Opens Local Users and Groups、 where you can manage user accounts and groups on the local machine。'),
('Microsoft Management Consoles（MSCs）','perfmon。msc','Opens Performance Monitor、 which allows you to monitor system performance metrics in real time。'),
('Microsoft Management Consoles（MSCs）','services。msc','Opens Services、 where you can manage the services running on the system、 including starting and stopping services。'),
('Microsoft Management Consoles（MSCs）','taskschd。msc','Opens Task Scheduler、 which allows you to schedule tasks and automate various system operations。'),
('Microsoft Management Consoles（MSCs）','tpm。msc','Opens the Trusted Platform Module （TPM） Management console for managing TPM hardware security features。'),
('Office 365','access','Open Access'),
('Office 365','excel','Open Excel'),
('Office 365','msteams','Open Teams'),
('Office 365','onenote','Open OneNote'),
('Office 365','outlook','Open Outlook'),
('Office 365','powerpnt','Open Powerpoint'),
('Office 365','winword','Open Word'),
('Open Browser','brave','Open Brave'),
('Open Browser','chrome','Open Chrome'),
('Open Browser','msedge','Open Edge'),
('Run Commands',' sfc /cachesize','System File Checker Utility （Set Cache Size to size x） sfc /cachesize=x'),
('Run Commands','calc、Calculator','CATEGORY'),
('Run Commands','charmap','Character Map'),
('Run Commands','chkdsk','Check Disk Utility'),
('Run Commands','cleanmgr','Disk Cleanup Utility'),
('Run Commands','cliconfg','SQL Client Configuration'),
('Run Commands','clipbrd','Clipboard Viewer'),
('Run Commands','cmd','Command Prompt'),
('Run Commands','control admintools','Administrative Tools'),
('Run Commands','control color','Display Properties （w/Appearance Tab Preselected）'),
('Run Commands','control desktop','Display Properties'),
('Run Commands','control folders','Folders Properties'),
('Run Commands','control fonts','Fonts'),
('Run Commands','control keyboard','Keyboard Properties'),
('Run Commands','control mouse','Mouse Properties'),
('Run Commands','control netconnections','Network Connections'),
('Run Commands','control printers','Printers and Faxes'),
('Run Commands','control schedtasks','Scheduled Tasks'),
('Run Commands','dcomcnfg','Component Services'),
('Run Commands','ddeshare','DDE Share'),
('Run Commands','diskpart','Disk Partition Manager'),
('Run Commands','drwtsn32','Dr。 Watson System Troubleshooting Utility'),
('Run Commands','dxdiag','Direct X Troubleshooter'),
('Run Commands','eudcedit','Private Character Editor'),
('Run Commands','fonts','Fonts Folder'),
('Run Commands','freecell','Free Cell Card Game'),
('Run Commands','fsquirt','Bluetooth Transfer Wizard'),
('Run Commands','iexpress','Iexpress Wizard'),
('Run Commands','ipconfig /all','IP Configuration （Display Connection Configuration）'),
('Run Commands','ipconfig /displaydns','IP Configuration （Display DNS Cache Contents）'),
('Run Commands','ipconfig /flushdns','IP Configuration （Delete DNS Cache Contents）'),
('Run Commands','ipconfig /registerdns','IP Configuration （Refreshes DHCP & ReーRegisters DNS）'),
('Run Commands','ipconfig /release','IP Configuration （Release All Connections）'),
('Run Commands','ipconfig /renew','IP Configuration （Renew All Connections）'),
('Run Commands','ipconfig /setclassid','IP Configuration （Modifies DHCP Class ID）'),
('Run Commands','ipconfig /showclassid','IP Configuration （Display DHCP Class ID）'),
('Run Commands','javaws','Java Control Panel （If Installed）'),
('Run Commands','logoff','Logs You Out Of Windows'),
('Run Commands','magnify','Windows Magnifier'),
('Run Commands','msconfig','System Configuration Utility'),
('Run Commands','mshearts','Hearts Card Game'),
('Run Commands','mstsc','Remote Desktop'),
('Run Commands','notepad、Notepad','CATEGORY'),
('Run Commands','osk','On Screen Keyboard'),
('Run Commands','packager','Object Packager'),
('Run Commands','perfmon','Performance Monitor'),
('Run Commands','printers','Printers Folder'),
('Run Commands','regedit','Registry Editor'),
('Run Commands','regedit32','Registry Editor'),
('Run Commands','sfc /purgecache','System File Checker Utility （Purge File Cache）'),
('Run Commands','sfc /revert','System File Checker Utility （Return to Default Setting） sfc /revert'),
('Run Commands','sfc /scanboot','System File Checker Utility （Scan On Every Boot）'),
('Run Commands','sfc /scannow','System File Checker Utility （Scan Immediately）'),
('Run Commands','sfc /scanonce','System File Checker Utility （Scan Once At Next Boot）'),
('Run Commands','shutdown','Shuts Down Windows'),
('Run Commands','sigverif','File Signature Verification Tool'),
('Run Commands','spider','Spider Solitare Card Game'),
('Run Commands','sysedit','System Configuration Editor'),
('Run Commands','syskey','Windows System Security Tool'),
('Run Commands','taskmgr','Task Manager'),
('Run Commands','telnet','Telnet Client'),
('Run Commands','tourstart','Windows XP Tour Wizard'),
('Run Commands','utilman','Utility Manager'),
('Run Commands','verifier','Driver Verifier Utility'),
('Run Commands','winchat','Microsoft Chat'),
('Run Commands','winmine','Minesweeper Game'),
('Run Commands','write、Wordpad','CATEGORY'),
('Run Commands','wupdmgr','Windows Update Launches'),
('Text editing shortcuts','Backspace','Delete characters to the left'),
('Text editing shortcuts','Ctrl ＋ =','Make selected text subscript'),
('Text editing shortcuts','Ctrl ＋ A','Select all text'),
('Text editing shortcuts','Ctrl ＋ B','Make selected text bold'),
('Text editing shortcuts','Ctrl ＋ Backspace','Delete words to the left'),
('Text editing shortcuts','Ctrl ＋ C','Copy text'),
('Text editing shortcuts','Ctrl ＋ Del','Delete words to the right'),
('Text editing shortcuts','Ctrl ＋ Down Arrow','Go to end of line break'),
('Text editing shortcuts','Ctrl ＋ End','Go to the end of the document'),
('Text editing shortcuts','Ctrl ＋ F','Find text'),
('Text editing shortcuts','Ctrl ＋ H','Find and replace text'),
('Text editing shortcuts','Ctrl ＋ Home','Go to the beginning of the document'),
('Text editing shortcuts','Ctrl ＋ I','Make selected text italic'),
('Text editing shortcuts','Ctrl ＋ Left Arrow','Go to beginning of previous word'),
('Text editing shortcuts','Ctrl ＋ Right Arrow','Go to beginning of next word'),
('Text editing shortcuts','Ctrl ＋ Shift ＋ =','Make selected text superscript'),
('Text editing shortcuts','Ctrl ＋ U','Underline selected text'),
('Text editing shortcuts','Ctrl ＋ Up Arrow','Go to beginning of line break'),
('Text editing shortcuts','Ctrl ＋ V','Paste text'),
('Text editing shortcuts','Ctrl ＋ X','Cut text'),
('Text editing shortcuts','Ctrl ＋ Y','Redo text'),
('Text editing shortcuts','Ctrl ＋ Z','Undo text'),
('Text editing shortcuts','Delete','Delete characters to the right'),
('Text editing shortcuts','Down Arrow','Go down one row'),
('Text editing shortcuts','End','Go to the end of the current line'),
('Text editing shortcuts','Home','Go to the beginning of the current line'),
('Text editing shortcuts','Left Arrow','Go to the left or to the end of previous line break'),
('Text editing shortcuts','Page Down','Move down one frame'),
('Text editing shortcuts','Page Up','Move up one frame'),
('Text editing shortcuts','Right Arrow','Go to the right or to the beginning of next line break'),
('Text editing shortcuts','Shift ＋ Ctrl ＋ Down','Select paragraphs to the right'),
('Text editing shortcuts','Shift ＋ Ctrl ＋ End','Select text between the cursor and the end of the document'),
('Text editing shortcuts','Shift ＋ Ctrl ＋ Home','Select text between the cursor and the beginning of the document'),
('Text editing shortcuts','Shift ＋ Ctrl ＋ Left','Select words to the left'),
('Text editing shortcuts','Shift ＋ Ctrl ＋ Right','Select words to the right'),
('Text editing shortcuts','Shift ＋ Ctrl ＋ Up','Select paragraphs to the left'),
('Text editing shortcuts','Shift ＋ Down Arrow','Select lines downwards'),
('Text editing shortcuts','Shift ＋ End','Select text between the cursor and the end of the current line'),
('Text editing shortcuts','Shift ＋ Home','Select text between the cursor and the beginning of the current line'),
('Text editing shortcuts','Shift ＋ Left Arrow','Select characters to the left'),
('Text editing shortcuts','Shift ＋ Page Down','Select one frame at a time of text below the cursor'),
('Text editing shortcuts','Shift ＋ Page Up','Select one frame at a time of text above the cursor'),
('Text editing shortcuts','Shift ＋ Right Arrow','Select characters to the right'),
('Text editing shortcuts','Shift ＋ Tab','Outdent'),
('Text editing shortcuts','Shift ＋ Up Arrow','Select lines upwards'),
('Text editing shortcuts','Use the following list of shortcuts to edit the text more quickly and efficiently。','CATEGORY'),
('Text indent shortcuts','Ctrl ＋ Shift ＋ click a taskbar button','Open an app as an administrator。'),
('Text indent shortcuts','Ctrl ＋ click a grouped taskbar button','Cycle through the windows of the group'),
('Text indent shortcuts','Shift ＋ click a taskbar button','Open an app or quickly open another instance of an app。'),
('Text indent shortcuts','Shift ＋ rightーclick a grouped taskbar button','Show the window menu for the group。'),
('Text indent shortcuts','Shift ＋ rightーclick a taskbar button','Show the window menu for the app。'),
('Text indent shortcuts','Taskbar Keyboard shortcuts','CATEGORY'),
('Text indent shortcuts','The below shortcuts allow you to navigate to the taskbar options quickly。 ','CATEGORY'),
('Text indent shortcuts','Up Arrow','Go up one row'),
('Windows Settings Page Shortcuts','Alt ＋ underline letter','Actions the setting identified by the letter。'),
('Windows Settings Page Shortcuts','Arrow keys','Select a button of the active setting。'),
('Windows Settings Page Shortcuts','Backspace','Opens the folder oneーlevel app in the Open or Save As dialog。'),
('Windows Settings Page Shortcuts','Ctrl ＋ Shift ＋ Tab','Cycles back through the tabs。'),
('Windows Settings Page Shortcuts','Ctrl ＋ Tab','Cycles forward through the tabs。'),
('Windows Settings Page Shortcuts','Ctrl ＋ number of tab','Jumps to tab position。'),
('Windows Settings Page Shortcuts','Shift ＋ Tab','Moves back through the settings。'),
('Windows Settings Page Shortcuts','Spacebar','Checks or clears the option in focus。'),
('Windows Settings Page Shortcuts','Tab','Moves forward through the settings。'),
('Windows Settings Page Shortcuts','Utilize the below shortcuts to navigate quickly on the Windows Settings page。','CATEGORY'),
('win_spec','calc','Open Calculator'),
('win_spec','charmap','Open Character Map'),
('win_spec','cleanmgr','Open Disk Cleanup'),
('win_spec','cmd','Open Command Prompt'),
('win_spec','control','Open Control Panel'),
('win_spec','dfrgui','Open Disk Defragmenter'),
('win_spec','dxdiag','Open DirectX Diagnostic Tool'),
('win_spec','eventvwr','Open Event Viewer'),
('win_spec','explorer','Open File Explorer'),
('win_spec','iexplore','Open Internet Explorer'),
('win_spec','magnify','Open Magnifier'),
('win_spec','msconfig','Open System Configuration'),
('win_spec','msinfo32','Open System Information'),
('win_spec','mspaint','Open Paint'),
('win_spec','notepad','Open Notepad'),
('win_spec','osk','Open OnーScreen Keyboard'),
('win_spec','perfmon','Open Performance Monitor'),
('win_spec','powershell ise','Open PowerShell ISE'),
('win_spec','regedit','Open Registry Editor'),
('win_spec','snippingtool','Open Snipping Tool'),
('win_spec','stikynot','Open Sticky Notes'),
('win_spec','sysedit','Open System Editor'),
('win_spec','taskmgr','Open Task Manager'),
('win_spec','wab','Open Windows Address Book'),
('win_spec','wabmig','Open Windows Address Book Migration Tool'),
('win_spec','winver','Open Windows Version Information'),
('win_spec','write','Open WordPad'),
('win_spec','wscript','Open Windows Script Host Settings');
